// ═══════════════════════════════════════
//  病院データベース v2 — 50病院 拡張版
// ═══════════════════════════════════════

export interface Hospital {
  id: number
  name: string
  region: string
  prefecture: string
  type: '大学病院' | '市中病院'
  beds: number
  residents: number           // 年間研修医採用数
  matchRate: number           // 最新倍率（数値）
  matchRateLabel: string      // 表示用（例: "4.2倍"）
  historicalRates: { year: number; rate: number }[]  // 過去3年倍率
  features: string[]
  specialties: string[]       // 強い診療科
  salaryNum: number           // 年収（万円、ソート用）
  salaryLabel: string         // 表示用
  busyness: 'high' | 'medium' | 'low'
  erType: 'ER型' | '各科当直型' | '混合型'
  deptScale: Record<string, 'S' | 'M' | 'L'>  // 診療科規模（スタッフ数ベース）
  isAnaba: boolean            // 穴場フラグ
  anabaReason?: string        // 穴場理由
  philosophy?: string         // 病院理念（面接用）
}

export const REGIONS = [
  '北海道', '東北', '関東', '中部', '近畿', '中国', '四国', '九州・沖縄',
]

export const HOSPITALS: Hospital[] = [
  // ── 関東 ──
  {
    id: 1, name: '聖路加国際病院', region: '関東', prefecture: '東京都',
    type: '市中病院', beds: 520, residents: 40,
    matchRate: 4.2, matchRateLabel: '4.2倍',
    historicalRates: [{ year: 2023, rate: 4.5 }, { year: 2024, rate: 4.3 }, { year: 2025, rate: 4.2 }],
    features: ['屋根瓦式', '英語カンファ', '海外研修'],
    specialties: ['内科', '外科', '救急科'],
    salaryNum: 450, salaryLabel: '約450万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '内科': 'L', '外科': 'L', '救急科': 'L', '小児科': 'M' },
    isAnaba: false,
    philosophy: '「キリスト教の愛の精神」に基づき、すべての人に最善の医療を提供する',
  },
  {
    id: 2, name: '亀田メディカルセンター', region: '関東', prefecture: '千葉県',
    type: '市中病院', beds: 865, residents: 36,
    matchRate: 3.8, matchRateLabel: '3.8倍',
    historicalRates: [{ year: 2023, rate: 4.1 }, { year: 2024, rate: 3.9 }, { year: 2025, rate: 3.8 }],
    features: ['ER型', '手技豊富', '寮完備'],
    specialties: ['救急科', '外科', '内科'],
    salaryNum: 500, salaryLabel: '約500万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '外科': 'L', '内科': 'L', '整形外科': 'M' },
    isAnaba: false,
    philosophy: 'すべては患者さんのために — Always Say YES!',
  },
  {
    id: 5, name: '虎の門病院', region: '関東', prefecture: '東京都',
    type: '市中病院', beds: 868, residents: 30,
    matchRate: 4.5, matchRateLabel: '4.5倍',
    historicalRates: [{ year: 2023, rate: 4.8 }, { year: 2024, rate: 4.6 }, { year: 2025, rate: 4.5 }],
    features: ['専門性高い', '研究機会', '都心立地'],
    specialties: ['内科', '血液内科', '内分泌'],
    salaryNum: 430, salaryLabel: '約430万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '血液内科': 'L', '外科': 'M', '内分泌': 'M' },
    isAnaba: false,
    philosophy: '高度専門医療を通じて社会に貢献する',
  },
  {
    id: 6, name: '東京大学医学部附属病院', region: '関東', prefecture: '東京都',
    type: '大学病院', beds: 1217, residents: 50,
    matchRate: 2.8, matchRateLabel: '2.8倍',
    historicalRates: [{ year: 2023, rate: 3.0 }, { year: 2024, rate: 2.9 }, { year: 2025, rate: 2.8 }],
    features: ['研究充実', '専門医取得', 'アカデミック'],
    specialties: ['内科', '外科', '小児科'],
    salaryNum: 350, salaryLabel: '約350万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '小児科': 'L', '精神科': 'M' },
    isAnaba: false,
    philosophy: '世界最高水準の医学・医療の実現と次世代リーダーの育成',
  },
  {
    id: 7, name: '慶應義塾大学病院', region: '関東', prefecture: '東京都',
    type: '大学病院', beds: 960, residents: 44,
    matchRate: 3.2, matchRateLabel: '3.2倍',
    historicalRates: [{ year: 2023, rate: 3.5 }, { year: 2024, rate: 3.3 }, { year: 2025, rate: 3.2 }],
    features: ['関連病院豊富', '研究', '人脈'],
    specialties: ['内科', '外科', '精神科'],
    salaryNum: 360, salaryLabel: '約360万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '精神科': 'M', '産婦人科': 'M' },
    isAnaba: false,
    philosophy: '先端医学・医療を推進し、人類の健康と福祉に貢献する',
  },
  {
    id: 8, name: '国立国際医療研究センター', region: '関東', prefecture: '東京都',
    type: '市中病院', beds: 781, residents: 22,
    matchRate: 3.6, matchRateLabel: '3.6倍',
    historicalRates: [{ year: 2023, rate: 3.4 }, { year: 2024, rate: 3.5 }, { year: 2025, rate: 3.6 }],
    features: ['グローバル', '感染症', '国際保健'],
    specialties: ['感染症', '内科', '救急科'],
    salaryNum: 450, salaryLabel: '約450万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '感染症': 'L', '内科': 'L', '救急科': 'M', '糖尿病': 'L' },
    isAnaba: false,
    philosophy: '国際医療協力と感染症対策を通じて世界の健康に貢献する',
  },
  {
    id: 11, name: '湘南鎌倉総合病院', region: '関東', prefecture: '神奈川県',
    type: '市中病院', beds: 658, residents: 24,
    matchRate: 3.1, matchRateLabel: '3.1倍',
    historicalRates: [{ year: 2023, rate: 3.4 }, { year: 2024, rate: 3.2 }, { year: 2025, rate: 3.1 }],
    features: ['救急豊富', '手技重視', '自由度高い'],
    specialties: ['救急科', '循環器', '外科'],
    salaryNum: 510, salaryLabel: '約510万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '循環器': 'L', '外科': 'M', '心臓外科': 'M' },
    isAnaba: false,
    philosophy: '生命だけは平等だ — 断らない救急医療',
  },
  {
    id: 16, name: '済生会横浜市東部病院', region: '関東', prefecture: '神奈川県',
    type: '市中病院', beds: 559, residents: 20,
    matchRate: 2.9, matchRateLabel: '2.9倍',
    historicalRates: [{ year: 2023, rate: 3.3 }, { year: 2024, rate: 3.1 }, { year: 2025, rate: 2.9 }],
    features: ['救急強い', '新しい施設', '横浜'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 480, salaryLabel: '約480万/年',
    busyness: 'medium', erType: 'ER型',
    deptScale: { '救急科': 'M', '内科': 'M', '外科': 'M' },
    isAnaba: true, anabaReason: '倍率が年々低下中（3.3→2.9）、穴場傾向',
    philosophy: '済生の精神に基づき、地域医療に貢献する',
  },
  {
    id: 18, name: '千葉大学医学部附属病院', region: '関東', prefecture: '千葉県',
    type: '大学病院', beds: 850, residents: 36,
    matchRate: 2.1, matchRateLabel: '2.1倍',
    historicalRates: [{ year: 2023, rate: 2.4 }, { year: 2024, rate: 2.2 }, { year: 2025, rate: 2.1 }],
    features: ['関東圏', '研究', 'バランス型'],
    specialties: ['内科', '外科', '皮膚科'],
    salaryNum: 350, salaryLabel: '約350万/年',
    busyness: 'low', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'M', '皮膚科': 'L' },
    isAnaba: true, anabaReason: '関東大学病院で倍率2倍台、入りやすい穴場',
    philosophy: 'つねに、より高きものをめざして',
  },
  {
    id: 19, name: '横浜市立大学附属病院', region: '関東', prefecture: '神奈川県',
    type: '大学病院', beds: 674, residents: 32,
    matchRate: 2.3, matchRateLabel: '2.3倍',
    historicalRates: [{ year: 2023, rate: 2.5 }, { year: 2024, rate: 2.4 }, { year: 2025, rate: 2.3 }],
    features: ['横浜', 'データサイエンス', '国際化'],
    specialties: ['内科', '外科', '産婦人科'],
    salaryNum: 350, salaryLabel: '約350万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'M', '外科': 'M', '産婦人科': 'M' },
    isAnaba: true, anabaReason: '横浜立地ながら倍率2.3倍と穏やか',
    philosophy: '実践的学術の精神で、先端医療と地域貢献を両立する',
  },
  {
    id: 21, name: '東京医科歯科大学病院', region: '関東', prefecture: '東京都',
    type: '大学病院', beds: 753, residents: 38,
    matchRate: 2.6, matchRateLabel: '2.6倍',
    historicalRates: [{ year: 2023, rate: 2.8 }, { year: 2024, rate: 2.7 }, { year: 2025, rate: 2.6 }],
    features: ['御茶ノ水', '研究', '医科歯科連携'],
    specialties: ['内科', '外科', '膠原病'],
    salaryNum: 360, salaryLabel: '約360万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'M', '膠原病': 'M', '歯科': 'L' },
    isAnaba: false,
    philosophy: '知と癒しの匠を創造し、人々の幸福に貢献する',
  },
  {
    id: 22, name: 'NTT東日本関東病院', region: '関東', prefecture: '東京都',
    type: '市中病院', beds: 594, residents: 18,
    matchRate: 2.5, matchRateLabel: '2.5倍',
    historicalRates: [{ year: 2023, rate: 2.8 }, { year: 2024, rate: 2.6 }, { year: 2025, rate: 2.5 }],
    features: ['五反田', '設備充実', 'ワークライフバランス'],
    specialties: ['内科', '外科', '泌尿器科'],
    salaryNum: 470, salaryLabel: '約470万/年',
    busyness: 'low', erType: '各科当直型',
    deptScale: { '内科': 'M', '外科': 'M', '泌尿器科': 'M' },
    isAnaba: true, anabaReason: '都心立地で倍率低下傾向、QOL重視派に人気',
    philosophy: '患者さんにやさしい高度な医療の実現',
  },
  {
    id: 23, name: '日本赤十字社医療センター', region: '関東', prefecture: '東京都',
    type: '市中病院', beds: 708, residents: 26,
    matchRate: 3.3, matchRateLabel: '3.3倍',
    historicalRates: [{ year: 2023, rate: 3.1 }, { year: 2024, rate: 3.2 }, { year: 2025, rate: 3.3 }],
    features: ['広尾', '産科強い', '国際赤十字'],
    specialties: ['産婦人科', '内科', '救急科'],
    salaryNum: 460, salaryLabel: '約460万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '産婦人科': 'L', '内科': 'L', '救急科': 'M', '小児科': 'M' },
    isAnaba: false,
    philosophy: '赤十字の人道・博愛の精神に基づく医療',
  },

  // ── 北海道 ──
  {
    id: 4, name: '手稲渓仁会病院', region: '北海道', prefecture: '北海道',
    type: '市中病院', beds: 670, residents: 28,
    matchRate: 3.0, matchRateLabel: '3.0倍',
    historicalRates: [{ year: 2023, rate: 3.3 }, { year: 2024, rate: 3.1 }, { year: 2025, rate: 3.0 }],
    features: ['ER型', '症例豊富', '教育充実'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 520, salaryLabel: '約520万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '内科': 'L', '外科': 'M' },
    isAnaba: false,
    philosophy: '医の心 — 信頼と安心の医療を提供する',
  },
  {
    id: 24, name: '旭川医科大学病院', region: '北海道', prefecture: '北海道',
    type: '大学病院', beds: 602, residents: 20,
    matchRate: 1.5, matchRateLabel: '1.5倍',
    historicalRates: [{ year: 2023, rate: 1.8 }, { year: 2024, rate: 1.6 }, { year: 2025, rate: 1.5 }],
    features: ['地域医療', '豊富な症例', '自然環境'],
    specialties: ['内科', '外科', '脳神経外科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'M', '外科': 'M', '脳神経外科': 'M' },
    isAnaba: true, anabaReason: '倍率1.5倍、地方大学病院で最も入りやすい部類',
    philosophy: '地域医療に根ざし、人間性豊かな医療人を育成する',
  },
  {
    id: 25, name: '北海道大学病院', region: '北海道', prefecture: '北海道',
    type: '大学病院', beds: 944, residents: 38,
    matchRate: 2.0, matchRateLabel: '2.0倍',
    historicalRates: [{ year: 2023, rate: 2.2 }, { year: 2024, rate: 2.1 }, { year: 2025, rate: 2.0 }],
    features: ['北海道最大', '研究充実', '広大キャンパス'],
    specialties: ['内科', '外科', '放射線科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '放射線科': 'M' },
    isAnaba: true, anabaReason: '旧帝大で倍率2.0倍、研究志向なら狙い目',
    philosophy: 'フロンティア精神で最先端医療を開拓する',
  },

  // ── 東北 ──
  {
    id: 17, name: '東北大学病院', region: '東北', prefecture: '宮城県',
    type: '大学病院', beds: 1225, residents: 38,
    matchRate: 2.0, matchRateLabel: '2.0倍',
    historicalRates: [{ year: 2023, rate: 2.3 }, { year: 2024, rate: 2.1 }, { year: 2025, rate: 2.0 }],
    features: ['東北最大', '研究', '災害医療'],
    specialties: ['内科', '外科', '小児科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '内科': 'L', '外科': 'L', '小児科': 'M', '脳神経外科': 'M' },
    isAnaba: true, anabaReason: '旧帝大で倍率低下中、東北での研修なら第一選択',
    philosophy: '研究第一主義 — 先進的医療で地域と世界に貢献する',
  },
  {
    id: 26, name: '仙台厚生病院', region: '東北', prefecture: '宮城県',
    type: '市中病院', beds: 393, residents: 12,
    matchRate: 2.2, matchRateLabel: '2.2倍',
    historicalRates: [{ year: 2023, rate: 2.5 }, { year: 2024, rate: 2.3 }, { year: 2025, rate: 2.2 }],
    features: ['循環器特化', '手技豊富', 'コンパクト'],
    specialties: ['循環器', '消化器', '内科'],
    salaryNum: 480, salaryLabel: '約480万/年',
    busyness: 'high', erType: '各科当直型',
    deptScale: { '循環器': 'L', '消化器': 'M', '内科': 'M' },
    isAnaba: true, anabaReason: '循環器志望なら穴場、少人数で手技機会多い',
    philosophy: '心臓・消化器の専門病院として高度医療を提供する',
  },

  // ── 中部 ──
  {
    id: 14, name: '名古屋大学医学部附属病院', region: '中部', prefecture: '愛知県',
    type: '大学病院', beds: 1080, residents: 40,
    matchRate: 2.2, matchRateLabel: '2.2倍',
    historicalRates: [{ year: 2023, rate: 2.5 }, { year: 2024, rate: 2.3 }, { year: 2025, rate: 2.2 }],
    features: ['中部最大', '研究', '関連病院多い'],
    specialties: ['内科', '外科', '整形外科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '整形外科': 'L' },
    isAnaba: false,
    philosophy: '勇気ある知識人を育て、先端医療で社会に貢献する',
  },
  {
    id: 27, name: '名古屋第二赤十字病院', region: '中部', prefecture: '愛知県',
    type: '市中病院', beds: 812, residents: 24,
    matchRate: 2.6, matchRateLabel: '2.6倍',
    historicalRates: [{ year: 2023, rate: 2.9 }, { year: 2024, rate: 2.7 }, { year: 2025, rate: 2.6 }],
    features: ['3次救急', '手技豊富', '名古屋'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 490, salaryLabel: '約490万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '内科': 'M', '外科': 'M' },
    isAnaba: true, anabaReason: '中部のER型で倍率低下傾向、救急志望に穴場',
    philosophy: '赤十字精神に基づく高度救急医療の実現',
  },
  {
    id: 28, name: '金沢大学附属病院', region: '中部', prefecture: '石川県',
    type: '大学病院', beds: 838, residents: 30,
    matchRate: 1.8, matchRateLabel: '1.8倍',
    historicalRates: [{ year: 2023, rate: 2.0 }, { year: 2024, rate: 1.9 }, { year: 2025, rate: 1.8 }],
    features: ['北陸最大', '研究', '金沢生活'],
    specialties: ['内科', '外科', '脳神経外科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'low', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'M', '脳神経外科': 'M' },
    isAnaba: true, anabaReason: '旧帝大級の環境で倍率1.8倍、QOL◎',
    philosophy: '地域と世界に開かれた教育病院として社会に貢献する',
  },
  {
    id: 29, name: '静岡県立総合病院', region: '中部', prefecture: '静岡県',
    type: '市中病院', beds: 712, residents: 20,
    matchRate: 2.0, matchRateLabel: '2.0倍',
    historicalRates: [{ year: 2023, rate: 2.3 }, { year: 2024, rate: 2.1 }, { year: 2025, rate: 2.0 }],
    features: ['県立基幹', 'バランス型', '静岡'],
    specialties: ['内科', '外科', '小児科'],
    salaryNum: 490, salaryLabel: '約490万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '内科': 'M', '外科': 'M', '小児科': 'M' },
    isAnaba: true, anabaReason: '関東に近い立地で倍率2.0倍、Uターン希望者に◎',
    philosophy: '県民の健康を守る最後の砦として高度医療を提供する',
  },

  // ── 近畿 ──
  {
    id: 9, name: '神戸市立医療センター中央市民病院', region: '近畿', prefecture: '兵庫県',
    type: '市中病院', beds: 768, residents: 28,
    matchRate: 3.4, matchRateLabel: '3.4倍',
    historicalRates: [{ year: 2023, rate: 3.6 }, { year: 2024, rate: 3.5 }, { year: 2025, rate: 3.4 }],
    features: ['救急搬送多い', '手技豊富', '教育体制◎'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 490, salaryLabel: '約490万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '内科': 'L', '外科': 'L' },
    isAnaba: false,
    philosophy: '市民の生命を守り、信頼される急性期病院をめざす',
  },
  {
    id: 10, name: '京都大学医学部附属病院', region: '近畿', prefecture: '京都府',
    type: '大学病院', beds: 1121, residents: 42,
    matchRate: 2.5, matchRateLabel: '2.5倍',
    historicalRates: [{ year: 2023, rate: 2.8 }, { year: 2024, rate: 2.6 }, { year: 2025, rate: 2.5 }],
    features: ['iPS研究', 'アカデミック', '伝統'],
    specialties: ['内科', '外科', '放射線科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '放射線科': 'M' },
    isAnaba: false,
    philosophy: '自由の学風のもと、世界最先端の医学研究と医療を追求する',
  },
  {
    id: 13, name: '大阪大学医学部附属病院', region: '近畿', prefecture: '大阪府',
    type: '大学病院', beds: 1086, residents: 46,
    matchRate: 2.4, matchRateLabel: '2.4倍',
    historicalRates: [{ year: 2023, rate: 2.7 }, { year: 2024, rate: 2.5 }, { year: 2025, rate: 2.4 }],
    features: ['先端医療', '研究充実', '免疫学'],
    specialties: ['内科', '外科', '小児科'],
    salaryNum: 350, salaryLabel: '約350万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '小児科': 'M', '免疫内科': 'L' },
    isAnaba: false,
    philosophy: '地域に生き世界に伸びる — 最先端の医療と研究',
  },
  {
    id: 20, name: '洛和会音羽病院', region: '近畿', prefecture: '京都府',
    type: '市中病院', beds: 472, residents: 16,
    matchRate: 2.4, matchRateLabel: '2.4倍',
    historicalRates: [{ year: 2023, rate: 2.6 }, { year: 2024, rate: 2.5 }, { year: 2025, rate: 2.4 }],
    features: ['総合内科', 'GIM', 'ケースカンファ充実'],
    specialties: ['総合診療科', '内科', '救急科'],
    salaryNum: 470, salaryLabel: '約470万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '総合診療科': 'L', '内科': 'M', '救急科': 'M' },
    isAnaba: true, anabaReason: '総合内科の聖地、GIM志望なら倍率2.4で狙い目',
    philosophy: '医療と介護の切れ目ないサービスで地域を支える',
  },
  {
    id: 30, name: '天理よろづ相談所病院', region: '近畿', prefecture: '奈良県',
    type: '市中病院', beds: 640, residents: 20,
    matchRate: 2.8, matchRateLabel: '2.8倍',
    historicalRates: [{ year: 2023, rate: 3.0 }, { year: 2024, rate: 2.9 }, { year: 2025, rate: 2.8 }],
    features: ['教育熱心', '内科充実', '寮完備'],
    specialties: ['内科', '血液内科', '感染症'],
    salaryNum: 460, salaryLabel: '約460万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '血液内科': 'L', '感染症': 'M' },
    isAnaba: false,
    philosophy: 'ようぼくの心で病む人に寄り添う医療を実践する',
  },
  {
    id: 31, name: '大阪医療センター', region: '近畿', prefecture: '大阪府',
    type: '市中病院', beds: 694, residents: 22,
    matchRate: 2.7, matchRateLabel: '2.7倍',
    historicalRates: [{ year: 2023, rate: 3.0 }, { year: 2024, rate: 2.8 }, { year: 2025, rate: 2.7 }],
    features: ['国立病院機構', '症例豊富', '大阪中心部'],
    specialties: ['内科', '外科', '救急科'],
    salaryNum: 470, salaryLabel: '約470万/年',
    busyness: 'high', erType: '混合型',
    deptScale: { '内科': 'L', '外科': 'M', '救急科': 'M' },
    isAnaba: true, anabaReason: '大阪中心部で倍率低下傾向、アクセス◎',
    philosophy: '国立病院として良質な医療を効率的に提供する',
  },

  // ── 中国 ──
  {
    id: 32, name: '広島大学病院', region: '中国', prefecture: '広島県',
    type: '大学病院', beds: 740, residents: 30,
    matchRate: 1.9, matchRateLabel: '1.9倍',
    historicalRates: [{ year: 2023, rate: 2.1 }, { year: 2024, rate: 2.0 }, { year: 2025, rate: 1.9 }],
    features: ['被ばく医療', '研究', '中国地方最大'],
    specialties: ['内科', '外科', '放射線科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'M', '放射線科': 'M' },
    isAnaba: true, anabaReason: '中国地方トップ大学病院で倍率1.9倍',
    philosophy: '被爆地ヒロシマの使命として平和と医療を追求する',
  },
  {
    id: 33, name: '倉敷中央病院', region: '中国', prefecture: '岡山県',
    type: '市中病院', beds: 1161, residents: 32,
    matchRate: 3.2, matchRateLabel: '3.2倍',
    historicalRates: [{ year: 2023, rate: 3.4 }, { year: 2024, rate: 3.3 }, { year: 2025, rate: 3.2 }],
    features: ['西日本最大級', '症例豊富', '教育充実'],
    specialties: ['内科', '外科', '心臓外科'],
    salaryNum: 500, salaryLabel: '約500万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '内科': 'L', '外科': 'L', '心臓外科': 'L', '循環器': 'L' },
    isAnaba: false,
    philosophy: '患者本位・地域貢献・教育重視の三位一体医療',
  },

  // ── 四国 ──
  {
    id: 34, name: '徳島大学病院', region: '四国', prefecture: '徳島県',
    type: '大学病院', beds: 697, residents: 22,
    matchRate: 1.4, matchRateLabel: '1.4倍',
    historicalRates: [{ year: 2023, rate: 1.7 }, { year: 2024, rate: 1.5 }, { year: 2025, rate: 1.4 }],
    features: ['四国', '地域医療', '少人数'],
    specialties: ['内科', '外科', '糖尿病'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'low', erType: '各科当直型',
    deptScale: { '内科': 'M', '外科': 'M', '糖尿病内科': 'M' },
    isAnaba: true, anabaReason: '倍率1.4倍、四国で最も入りやすい大学病院',
    philosophy: '自覚と責任ある医療人を育成する',
  },
  {
    id: 35, name: '松山赤十字病院', region: '四国', prefecture: '愛媛県',
    type: '市中病院', beds: 585, residents: 14,
    matchRate: 1.8, matchRateLabel: '1.8倍',
    historicalRates: [{ year: 2023, rate: 2.0 }, { year: 2024, rate: 1.9 }, { year: 2025, rate: 1.8 }],
    features: ['四国ER', '地域密着', '温暖'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 470, salaryLabel: '約470万/年',
    busyness: 'medium', erType: 'ER型',
    deptScale: { '救急科': 'M', '内科': 'M', '外科': 'M' },
    isAnaba: true, anabaReason: 'ER型で倍率1.8倍、四国の救急研修穴場',
    philosophy: '赤十字精神に基づき、愛媛の地域医療を守る',
  },

  // ── 九州・沖縄 ──
  {
    id: 3, name: '沖縄県立中部病院', region: '九州・沖縄', prefecture: '沖縄県',
    type: '市中病院', beds: 550, residents: 24,
    matchRate: 3.5, matchRateLabel: '3.5倍',
    historicalRates: [{ year: 2023, rate: 3.8 }, { year: 2024, rate: 3.6 }, { year: 2025, rate: 3.5 }],
    features: ['米国式', '症例豊富', '離島研修'],
    specialties: ['救急科', '総合診療科', '内科'],
    salaryNum: 480, salaryLabel: '約480万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '総合診療科': 'L', '内科': 'M' },
    isAnaba: false,
    philosophy: '米国式臨床教育をベースに、実践力のある医師を育てる',
  },
  {
    id: 12, name: '飯塚病院', region: '九州・沖縄', prefecture: '福岡県',
    type: '市中病院', beds: 1048, residents: 30,
    matchRate: 2.6, matchRateLabel: '2.6倍',
    historicalRates: [{ year: 2023, rate: 2.8 }, { year: 2024, rate: 2.7 }, { year: 2025, rate: 2.6 }],
    features: ['総合診療', '教育熱心', '症例豊富'],
    specialties: ['総合診療科', '内科', '外科'],
    salaryNum: 500, salaryLabel: '約500万/年',
    busyness: 'high', erType: '混合型',
    deptScale: { '総合診療科': 'L', '内科': 'L', '外科': 'M' },
    isAnaba: false,
    philosophy: 'We Deliver The Best — 地域医療を学ぶ最前線',
  },
  {
    id: 15, name: '九州大学病院', region: '九州・沖縄', prefecture: '福岡県',
    type: '大学病院', beds: 1275, residents: 44,
    matchRate: 2.3, matchRateLabel: '2.3倍',
    historicalRates: [{ year: 2023, rate: 2.6 }, { year: 2024, rate: 2.4 }, { year: 2025, rate: 2.3 }],
    features: ['九州トップ', '研究', '専門医取得'],
    specialties: ['内科', '外科', '放射線科'],
    salaryNum: 350, salaryLabel: '約350万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'L', '放射線科': 'M' },
    isAnaba: false,
    philosophy: '自律的に改革し続ける大学 — 九州から世界へ',
  },
  {
    id: 36, name: '済生会福岡総合病院', region: '九州・沖縄', prefecture: '福岡県',
    type: '市中病院', beds: 385, residents: 14,
    matchRate: 2.0, matchRateLabel: '2.0倍',
    historicalRates: [{ year: 2023, rate: 2.4 }, { year: 2024, rate: 2.2 }, { year: 2025, rate: 2.0 }],
    features: ['天神', 'コンパクト', '福岡生活'],
    specialties: ['内科', '外科', '循環器'],
    salaryNum: 470, salaryLabel: '約470万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '内科': 'M', '外科': 'S', '循環器': 'M' },
    isAnaba: true, anabaReason: '福岡天神で倍率2.0倍、生活環境最高',
    philosophy: '済生の精神で福岡の地域医療を支える',
  },
  {
    id: 37, name: '長崎大学病院', region: '九州・沖縄', prefecture: '長崎県',
    type: '大学病院', beds: 862, residents: 28,
    matchRate: 1.7, matchRateLabel: '1.7倍',
    historicalRates: [{ year: 2023, rate: 1.9 }, { year: 2024, rate: 1.8 }, { year: 2025, rate: 1.7 }],
    features: ['熱帯医学', '感染症', '国際保健'],
    specialties: ['感染症', '内科', '外科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'low', erType: '各科当直型',
    deptScale: { '感染症': 'L', '内科': 'M', '外科': 'M' },
    isAnaba: true, anabaReason: '熱帯医学研究所併設、感染症志望の穴場',
    philosophy: '出島の精神で世界と繋がる医学教育と研究',
  },
  {
    id: 38, name: '熊本大学病院', region: '九州・沖縄', prefecture: '熊本県',
    type: '大学病院', beds: 845, residents: 32,
    matchRate: 1.8, matchRateLabel: '1.8倍',
    historicalRates: [{ year: 2023, rate: 2.1 }, { year: 2024, rate: 1.9 }, { year: 2025, rate: 1.8 }],
    features: ['ECFMG認定', '循環器', '地域貢献'],
    specialties: ['循環器', '内科', '外科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '循環器': 'L', '内科': 'L', '外科': 'M' },
    isAnaba: true, anabaReason: 'ECFMG認定、倍率1.8倍で九州穴場',
    philosophy: '創造と進取の精神で社会貢献する医療人を育成する',
  },
  {
    id: 39, name: '沖縄県立南部医療センター', region: '九州・沖縄', prefecture: '沖縄県',
    type: '市中病院', beds: 434, residents: 14,
    matchRate: 2.2, matchRateLabel: '2.2倍',
    historicalRates: [{ year: 2023, rate: 2.5 }, { year: 2024, rate: 2.3 }, { year: 2025, rate: 2.2 }],
    features: ['沖縄第2', '周産期', '外傷'],
    specialties: ['救急科', '産婦人科', '外科'],
    salaryNum: 480, salaryLabel: '約480万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'M', '産婦人科': 'M', '外科': 'M' },
    isAnaba: true, anabaReason: '中部病院の陰に隠れた穴場、同等の救急経験',
    philosophy: '沖縄の県民医療を守る南部の砦',
  },

  // ── 追加の関東・近畿 人気病院 ──
  {
    id: 40, name: '東京都立多摩総合医療センター', region: '関東', prefecture: '東京都',
    type: '市中病院', beds: 789, residents: 20,
    matchRate: 2.8, matchRateLabel: '2.8倍',
    historicalRates: [{ year: 2023, rate: 3.0 }, { year: 2024, rate: 2.9 }, { year: 2025, rate: 2.8 }],
    features: ['都立', '3次救急', '多摩地区'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 480, salaryLabel: '約480万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '内科': 'M', '外科': 'M' },
    isAnaba: false,
    philosophy: '都民の生命と健康を守る最後の砦',
  },
  {
    id: 41, name: '聖マリアンナ医科大学病院', region: '関東', prefecture: '神奈川県',
    type: '大学病院', beds: 1208, residents: 40,
    matchRate: 2.0, matchRateLabel: '2.0倍',
    historicalRates: [{ year: 2023, rate: 2.3 }, { year: 2024, rate: 2.1 }, { year: 2025, rate: 2.0 }],
    features: ['私立大学', '救急', '川崎'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 380, salaryLabel: '約380万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '救急科': 'M', '内科': 'L', '外科': 'M' },
    isAnaba: true, anabaReason: '関東大学病院で倍率2.0倍、入りやすい',
    philosophy: 'キリスト教的人類愛に基づく生命の尊厳を大切にする医療',
  },
  {
    id: 42, name: '市立札幌病院', region: '北海道', prefecture: '北海道',
    type: '市中病院', beds: 672, residents: 16,
    matchRate: 1.9, matchRateLabel: '1.9倍',
    historicalRates: [{ year: 2023, rate: 2.2 }, { year: 2024, rate: 2.0 }, { year: 2025, rate: 1.9 }],
    features: ['札幌市立', '症例豊富', '生活便利'],
    specialties: ['内科', '外科', '小児科'],
    salaryNum: 490, salaryLabel: '約490万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '内科': 'M', '外科': 'M', '小児科': 'M' },
    isAnaba: true, anabaReason: '札幌市内で倍率1.9倍、生活環境◎の穴場',
    philosophy: '市民に信頼される高度急性期医療を提供する',
  },
  {
    id: 43, name: '岡山大学病院', region: '中国', prefecture: '岡山県',
    type: '大学病院', beds: 865, residents: 34,
    matchRate: 2.0, matchRateLabel: '2.0倍',
    historicalRates: [{ year: 2023, rate: 2.3 }, { year: 2024, rate: 2.1 }, { year: 2025, rate: 2.0 }],
    features: ['中四国拠点', '研究', '災害医療'],
    specialties: ['内科', '外科', '小児科'],
    salaryNum: 340, salaryLabel: '約340万/年',
    busyness: 'medium', erType: '各科当直型',
    deptScale: { '内科': 'L', '外科': 'M', '小児科': 'M' },
    isAnaba: true, anabaReason: '中四国最大拠点で倍率2.0倍、研究志向穴場',
    philosophy: '高度な知の創成と地域への貢献',
  },
  {
    id: 44, name: '北里大学病院', region: '関東', prefecture: '神奈川県',
    type: '大学病院', beds: 1033, residents: 36,
    matchRate: 2.4, matchRateLabel: '2.4倍',
    historicalRates: [{ year: 2023, rate: 2.6 }, { year: 2024, rate: 2.5 }, { year: 2025, rate: 2.4 }],
    features: ['相模原', '救急', 'チーム医療'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 370, salaryLabel: '約370万/年',
    busyness: 'medium', erType: '混合型',
    deptScale: { '救急科': 'L', '内科': 'L', '外科': 'M' },
    isAnaba: false,
    philosophy: '開拓・報恩・叡智と実践の精神で医療に貢献する',
  },
  {
    id: 45, name: '兵庫県立尼崎総合医療センター', region: '近畿', prefecture: '兵庫県',
    type: '市中病院', beds: 730, residents: 18,
    matchRate: 2.3, matchRateLabel: '2.3倍',
    historicalRates: [{ year: 2023, rate: 2.6 }, { year: 2024, rate: 2.4 }, { year: 2025, rate: 2.3 }],
    features: ['新設', '救急強い', '大阪近い'],
    specialties: ['救急科', '内科', '外科'],
    salaryNum: 480, salaryLabel: '約480万/年',
    busyness: 'high', erType: 'ER型',
    deptScale: { '救急科': 'L', '内科': 'M', '外科': 'M' },
    isAnaba: true, anabaReason: '2015年新設で知名度低いが施設最新、穴場',
    philosophy: '県民の安全・安心を支える高度急性期医療',
  },
]

// ── フィルタ用定数 ──
export const ALL_SPECIALTIES = Array.from(
  new Set(HOSPITALS.flatMap(h => h.specialties))
).sort()

export const BUSYNESS_LABELS: Record<string, string> = {
  high: '忙しい',
  medium: '普通',
  low: 'ゆるめ',
}

export const ER_TYPES = ['ER型', '各科当直型', '混合型'] as const

export const SALARY_RANGES = [
  { label: '〜400万', min: 0, max: 400 },
  { label: '400〜470万', min: 400, max: 470 },
  { label: '470〜500万', min: 470, max: 500 },
  { label: '500万〜', min: 500, max: 9999 },
] as const

export const MATCH_RATE_RANGES = [
  { label: '〜2.0倍（入りやすい）', min: 0, max: 2.0 },
  { label: '2.0〜3.0倍', min: 2.0, max: 3.0 },
  { label: '3.0〜4.0倍', min: 3.0, max: 4.0 },
  { label: '4.0倍〜（激戦）', min: 4.0, max: 99 },
] as const
