'use client'
import DrugCompareLayout, { CompareData } from '@/components/compare/DrugCompareLayout'

const data: CompareData = {
  slug: 'sglt2i',
  category: '糖尿病治療薬',
  title: 'SGLT2阻害薬 比較表',
  description: 'エンパグリフロジン・ダパグリフロジン・カナグリフロジン・イプラグリフロジン・トホグリフロジン・ルセオグリフロジンの6剤を比較。心腎保護エビデンス・適応の違い。',
  columns: ['generic', 'brand', 'indication', 'halfLife', 'metabolism', 'renalAdjust', 'features', 'evidence'],
  drugs: [
    {
      generic: 'エンパグリフロジン',
      brand: 'ジャディアンス',
      specs: '10mg/25mg 錠',
      indication: '2型糖尿病、慢性心不全（HFrEF/HFpEF）、CKD',
      halfLife: '約12.4時間',
      metabolism: 'グルクロン酸抱合（UGT2B7/1A3/1A9）',
      renalAdjust: 'eGFR < 20: 新規投与は一般的でない（心不全・CKD適応では継続可能な場合あり）',
      features: '心血管アウトカム改善のエビデンスが最も早く確立。心不全適応（HFrEF/HFpEF両方）あり。CKD適応あり。1型糖尿病は禁忌',
      contraindication: '重症ケトーシス、糖尿病性昏睡、重症感染症、1型糖尿病',
      evidence: 'EMPA-REG OUTCOME、EMPEROR-Reduced/Preserved、EMPA-KIDNEY',
    },
    {
      generic: 'ダパグリフロジン',
      brand: 'フォシーガ',
      specs: '5mg/10mg 錠',
      indication: '2型糖尿病、1型糖尿病（日本）、慢性心不全、CKD',
      halfLife: '約12.9時間',
      metabolism: 'グルクロン酸抱合（UGT1A9）',
      renalAdjust: 'eGFR < 25: 新規投与は一般的でない（心不全・CKD適応では継続可能な場合あり）',
      features: '日本で唯一1型糖尿病にも適応あり（インスリン併用下）。心不全（HFrEF）・CKD適応あり。適応が最も広い',
      contraindication: '重症ケトーシス、糖尿病性昏睡、重症感染症',
      evidence: 'DECLARE-TIMI 58、DAPA-HF、DAPA-CKD',
    },
    {
      generic: 'カナグリフロジン',
      brand: 'カナグル',
      specs: '100mg 錠',
      indication: '2型糖尿病',
      halfLife: '約10.6時間',
      metabolism: 'グルクロン酸抱合（UGT1A9/2B4）',
      renalAdjust: 'eGFR < 30: 効果減弱のため一般的でない',
      features: 'SGLT1にも一部作用（消化管での糖吸収抑制）。体重減少効果がやや強い。CANVAS試験で下肢切断リスク上昇が報告（その後の試験では否定的）',
      contraindication: '重症ケトーシス、糖尿病性昏睡、重症感染症、1型糖尿病',
      evidence: 'CANVAS、CREDENCE（CKD）',
    },
    {
      generic: 'イプラグリフロジン',
      brand: 'スーグラ',
      specs: '25mg/50mg 錠',
      indication: '2型糖尿病、1型糖尿病（インスリン併用）',
      halfLife: '約15時間',
      metabolism: 'グルクロン酸抱合（UGT2B7）',
      renalAdjust: '中等度以上の腎障害: 効果減弱',
      features: '日本発のSGLT2阻害薬。1型糖尿病にも適応あり。SGLT2選択性が高い',
      contraindication: '重症ケトーシス、糖尿病性昏睡、重症感染症',
      evidence: 'STELLA-LONG TERM',
    },
    {
      generic: 'トホグリフロジン',
      brand: 'デベルザ/アプルウェイ',
      specs: '20mg 錠',
      indication: '2型糖尿病',
      halfLife: '約5.4時間',
      metabolism: 'CYP2C18/4A11/4F3B、グルクロン酸抱合',
      renalAdjust: '中等度以上の腎障害: 効果減弱',
      features: 'SGLT2選択性がクラス最高。半減期が短い。日本発',
      contraindication: '重症ケトーシス、糖尿病性昏睡、重症感染症、1型糖尿病',
      evidence: '国内臨床試験',
    },
    {
      generic: 'ルセオグリフロジン',
      brand: 'ルセフィ',
      specs: '2.5mg/5mg 錠',
      indication: '2型糖尿病',
      halfLife: '約11時間',
      metabolism: 'CYP3A4/4A11/4F3B、グルクロン酸抱合',
      renalAdjust: '中等度以上の腎障害: 効果減弱',
      features: '日本発。SGLT2選択性が高い。低用量から使用可能',
      contraindication: '重症ケトーシス、糖尿病性昏睡、重症感染症、1型糖尿病',
      evidence: '国内臨床試験',
    },
  ],
  seoContent: [
    { heading: 'SGLT2阻害薬の心腎保護効果', text: 'SGLT2阻害薬は血糖降下に加え、心不全入院の減少・腎機能低下抑制・心血管死亡減少というマルチベネフィットが大規模試験で証明されています。特にエンパグリフロジン（EMPA-REG OUTCOME）とダパグリフロジン（DAPA-HF、DAPA-CKD）は非糖尿病患者の心不全・CKDにも適応が拡大しています。' },
    { heading: 'ケトアシドーシスのリスク', text: 'SGLT2阻害薬の重要な副作用として正常血糖ケトアシドーシス（euDKA）があります。血糖は正常〜軽度上昇にもかかわらずケトン産生が亢進するため、発見が遅れやすい点が問題です。手術前・脱水時・シックデイには休薬が示されます。' },
    { heading: '性器感染症・尿路感染症', text: 'SGLT2阻害薬は尿中糖排泄を増加させるため、性器カンジダ症・尿路感染症のリスクが上昇します。特に女性で頻度が高く、使用開始時の説明が重要です。陰部の清潔保持と症状出現時の早期受診を指導します。' },
  ],
  references: [
    '各薬剤の添付文書（最新版）',
    'Zinman B et al. Empagliflozin (EMPA-REG OUTCOME). N Engl J Med 2015;373:2117-2128',
    'McMurray JJV et al. Dapagliflozin in heart failure (DAPA-HF). N Engl J Med 2019;381:1995-2008',
    'Heerspink HJL et al. Dapagliflozin in CKD (DAPA-CKD). N Engl J Med 2020;383:1436-1446',
    '日本糖尿病学会. 糖尿病治療ガイド 2024-2025',
  ],
  relatedTools: [
    { href: '/tools/calc/egfr', name: 'eGFR' },
    { href: '/compare/dpp4i', name: 'DPP-4阻害薬比較' },
    { href: '/compare/arb', name: 'ARB比較' },
  ],
}

export default function SGLT2iComparePage() {
  return <DrugCompareLayout data={data} />
}
