// カテゴリ定義（クラスターA-R: SEO_GUIDELINE.md・キーワードリスト準拠）
export const categories = {
  'josler-basics': { name: 'J-OSLER基礎', cluster: 'A' },
  'case-registration': { name: '症例登録', cluster: 'B' },
  'medical-history': { name: '病歴要約', cluster: 'C' },
  'disease-specific': { name: '疾患別病歴要約', cluster: 'D' },
  'progress-management': { name: '進捗管理', cluster: 'E' },
  'jmecc-training': { name: 'JMECC・講習', cluster: 'F' },
  'specialist-exam': { name: '内科専門医試験', cluster: 'G' },
  'exam-by-field': { name: '試験領域別', cluster: 'H' },
  'comprehensive-exam': { name: '総合内科専門医', cluster: 'I' },
  'ai-tools': { name: 'AI・ツール', cluster: 'J' },
  'mental-life': { name: 'メンタル・生活', cluster: 'K' },
  'part-time': { name: 'バイト・収入', cluster: 'L' },
  'tax-saving': { name: '税金・節税', cluster: 'M' },
  'career': { name: 'キャリア', cluster: 'N' },
  'academic': { name: '学会・論文', cluster: 'O' },
  'life-events': { name: '結婚・出産', cluster: 'P' },
  'subspecialty': { name: 'サブスペJ-OSLER', cluster: 'Q' },
  'others': { name: 'その他', cluster: 'R' },
} as const

export type CategorySlug = keyof typeof categories

// クラスターカラー（A-R: SEO_GUIDELINE.md・キーワードリスト準拠）
export const clusterColors = {
  A: { bg: '#1E3A5F', name: 'J-OSLER基礎' },
  B: { bg: '#3D5A80', name: '症例登録' },
  C: { bg: '#1B4F3A', name: '病歴要約' },
  D: { bg: '#2D6A4F', name: '疾患別病歴要約' },
  E: { bg: '#0D7377', name: '進捗管理' },
  F: { bg: '#4A5568', name: 'JMECC・講習' },
  G: { bg: '#7F1D1D', name: '内科専門医試験' },
  H: { bg: '#9B2C2C', name: '試験領域別' },
  I: { bg: '#B7410E', name: '総合内科専門医' },
  J: { bg: '#4338CA', name: 'AI・ツール' },
  K: { bg: '#134E4A', name: 'メンタル・生活' },
  L: { bg: '#4C1D95', name: 'バイト・収入' },
  M: { bg: '#92400E', name: '税金・節税' },
  N: { bg: '#2B6CB0', name: 'キャリア' },
  O: { bg: '#6D28D9', name: '学会・論文' },
  P: { bg: '#9D174D', name: '結婚・出産' },
  Q: { bg: '#5B6ABF', name: 'サブスペJ-OSLER' },
  R: { bg: '#6B6760', name: 'その他' },
} as const

export type ClusterId = keyof typeof clusterColors

// ピラーページ定義（SEO_GUIDELINE.md クラスター構成図準拠）
export const pillarPages = {
  'josler-complete-guide': {
    title: 'J-OSLER完全攻略ガイド',
    clusters: ['A', 'B', 'C', 'D', 'E', 'F'],
  },
  'exam-preparation-guide': {
    title: '内科専門医試験対策ガイド',
    clusters: ['G', 'H', 'I'],
  },
  'efficiency-guide': {
    title: '内科専攻医の効率化ガイド',
    clusters: ['J'],
  },
  'money-career-guide': {
    title: '内科専攻医のお金とキャリア',
    clusters: ['K', 'L', 'M', 'N', 'O', 'P'],
  },
} as const

// CTA設定
export const ctaConfig = {
  template: {
    title: '🚀 AIが病歴要約の下書きを30秒で生成',
    description: '症例情報を入力するだけ。総合考察・全人的視点も自動で構成。手書き3時間→30分に短縮した専攻医が続出中。',
    buttonText: '無料で試してみる',
    url: '/pro',
  },
  progress: {
    title: '🚀 AIが病歴要約の下書きを30秒で生成',
    description: 'J-OSLER作業を10分の1に。症例登録テンプレ・検査値フォーマット変換・病歴要約AI下書きが全部入り。',
    buttonText: '無料で試してみる',
    url: '/pro',
  },
  quiz: {
    title: '🚀 AIが病歴要約の下書きを30秒で生成',
    description: 'J-OSLER作業を10分の1に。症例登録テンプレ・検査値フォーマット変換・病歴要約AI下書きが全部入り。',
    buttonText: '無料で試してみる',
    url: '/pro',
  },
  checklist: {
    title: '🚀 AIが病歴要約の下書きを30秒で生成',
    description: 'J-OSLER作業を10分の1に。症例登録テンプレ・検査値フォーマット変換・病歴要約AI下書きが全部入り。',
    buttonText: '無料で試してみる',
    url: '/pro',
  },
  general: {
    title: '🚀 AIが病歴要約の下書きを30秒で生成',
    description: 'J-OSLER作業を10分の1に。症例登録テンプレ・検査値フォーマット変換・病歴要約AI下書きが全部入り。',
    buttonText: '無料で試してみる',
    url: '/pro',
  },
} as const

export type CtaType = keyof typeof ctaConfig

// タグ → URLスラッグ変換（Cloudflare Pagesで日本語パスが404になるため英語スラッグを使用）
export const tagSlugMap: Record<string, string> = {
  'J-OSLER': 'j-osler',
  '修了要件': 'completion-requirements',
  '内科専門医': 'naika-senmonni',
  '症例登録': 'case-registration',
  '病歴要約': 'medical-history',
  '書き方': 'how-to-write',
  'テンプレート': 'template',
  '内科専攻医': 'naika-senkoui',
  '効率化': 'efficiency',
  '疾患群': 'disease-group',
  '自己省察': 'self-reflection',
  'コピペ': 'copy-paste',
  '総合考察': 'comprehensive-discussion',
  '全人的視点': 'holistic-perspective',
  '差し戻し': 'revision',
  'Accept': 'accept',
  '160症例': '160-cases',
  '120症例': '120-cases',
  '29症例': '29-cases',
  '7期生': '7th-cohort',
  '選び方': 'how-to-choose',
  '1年目': '1st-year',
  '2026年': '2026',
  '2年目': '2nd-year',
  '360度評価': '360-evaluation',
  '3年目': '3rd-year',
  '56疾患群': '56-disease-groups',
  '8期生': '8th-cohort',
  'A4': 'a4',
  'AI': 'ai',
  'AIプロンプト': 'ai-prompt',
  'AI活用': 'ai-utilization',
  'AKI': 'aki',
  'CKD': 'ckd',
  'COPD': 'copd',
  'ChatGPT': 'chatgpt',
  'Claude': 'claude',
  'ICLS': 'icls',
  'J-OSLER承認': 'j-osler-approval',
  'JMECC': 'jmecc',
  'MBI': 'mbi',
  'MCP': 'mcp',
  'NISA': 'nisa',
  'Notion': 'notion',
  'Perplexity': 'perplexity',
  'PubMed': 'pubmed',
  'QBオンライン': 'qb-online',
  'Reject': 'reject',
  'Revision': 'revision-status',
  'SLE': 'sle',
  'UpToDate': 'uptodate',
  'WHO推奨': 'who-recommendation',
  'Word': 'word',
  'e-Learning': 'e-learning',
  'iDeCo': 'ideco',
  'iPhone': 'iphone',
  'いつから': 'when-to-start',
  'おすすめ': 'recommended',
  'おすすめ教材': 'recommended-materials',
  'てんかん': 'epilepsy',
  'ふるさと納税': 'furusato-nozei',
  'アカデミックキャリア': 'academic-career',
  'アルバイト': 'part-time',
  'アレルギー': 'allergy',
  'イヤーノート': 'year-note',
  'エラー': 'error',
  'ガイドライン': 'guideline',
  'キャリア': 'career',
  'クロノタイプ': 'chronotype',
  'ケースレポート': 'case-report',
  'コミュニケーション': 'communication',
  'コンビニ': 'convenience-store',
  'サブスペシャリティ': 'subspecialty',
  'サブスペシャルティ': 'subspecialty',
  'ショック': 'shock',
  'スケジュール': 'schedule',
  'ストレス管理': 'stress-management',
  'スマホ': 'smartphone',
  'タスク管理': 'task-management',
  'チェックリスト': 'checklist',
  'ツール': 'tools',
  'テキスト': 'textbook',
  'トラブル': 'trouble',
  'ネフローゼ症候群': 'nephrotic-syndrome',
  'バイト': 'part-time-job',
  'バイト収入': 'part-time-income',
  'バイト相場': 'part-time-rate',
  'バーンアウト': 'burnout',
  'パスワード': 'password',
  'パパ育休': 'paternity-leave',
  'パーキンソン病': 'parkinsons-disease',
  'フェローシップ': 'fellowship',
  'フォーマット': 'format',
  'プログラム': 'program',
  'プログラム変更': 'program-change',
  'プログラム統括責任者': 'program-director',
  'プロンプト': 'prompt',
  'ポスター発表': 'poster-presentation',
  'マインドフルネス': 'mindfulness',
  'メタ認知': 'metacognition',
  'メンタル': 'mental-health',
  'モバイル': 'mobile',
  'ライフイベント': 'life-events',
  'リンパ腫': 'lymphoma',
  'ログイン': 'login',
  'ログインできない': 'login-error',
  'ロードマップ': 'roadmap',
  'ワークライフバランス': 'work-life-balance',
  '一次評価': 'first-evaluation',
  '一覧': 'list',
  '不具合': 'bug',
  '不合格': 'failed-exam',
  '不整脈': 'arrhythmia',
  '事前準備': 'preparation',
  '二次評価': 'second-evaluation',
  '仕事術': 'work-skills',
  '代謝': 'metabolism',
  '住民税': 'resident-tax',
  '使い方': 'how-to-use',
  '例文': 'example',
  '保活': 'daycare-activities',
  '保育園': 'daycare',
  '修了後': 'after-completion',
  '修了見込': 'expected-completion',
  '修了認定': 'completion-certification',
  '健康診断': 'health-checkup',
  '健診バイト': 'checkup-parttime',
  '入院後経過': 'hospitalization-course',
  '全身麻酔': 'general-anesthesia',
  '共働き': 'dual-income',
  '共通講習': 'common-lecture',
  '内分泌': 'endocrinology',
  '内科 キャリア': 'internal-medicine-career',
  '内科専門医 キャリア': 'specialist-career',
  '内科専門医試験': 'specialist-exam',
  '内科救急': 'internal-emergency',
  '再受験': 'retake-exam',
  '再登録': 're-registration',
  '出産': 'childbirth',
  '出題傾向': 'exam-trend',
  '出願': 'application',
  '出願期間': 'application-period',
  '分量': 'length',
  '初期研修': 'initial-training',
  '剖検症例': 'autopsy-case',
  '副収入': 'side-income',
  '副業': 'side-job',
  '副業収入': 'side-job-income',
  '副腎': 'adrenal',
  '勉強時間': 'study-time',
  '勉強法': 'study-method',
  '勉強開始時期': 'study-start-timing',
  '医学英語': 'medical-english',
  '医学論文': 'medical-paper',
  '医師': 'doctor',
  '医師 バイト': 'doctor-parttime',
  '医師 結婚相手': 'doctor-marriage-partner',
  '医師働き方改革': 'doctor-work-reform',
  '医師転職': 'doctor-career-change',
  '医療倫理': 'medical-ethics',
  '医療安全': 'medical-safety',
  '単位': 'credits',
  '参考文献': 'references',
  '参考書': 'reference-book',
  '収入': 'income',
  '受験申し込み': 'exam-application',
  '受験資格': 'exam-eligibility',
  '口演': 'oral-presentation',
  '合格率': 'pass-rate',
  '呼吸器': 'respiratory',
  '問題集': 'question-book',
  '国試': 'national-exam',
  '報酬': 'compensation',
  '変更点': 'changes',
  '外来': 'outpatient',
  '外来バイト': 'outpatient-parttime',
  '外来症例': 'outpatient-case',
  '外科紹介症例': 'surgical-referral-case',
  '多職種評価': 'multidisciplinary-evaluation',
  '多職種連携': 'multidisciplinary-teamwork',
  '大学病院': 'university-hospital',
  '大学院': 'graduate-school',
  '女性医師': 'female-doctor',
  '妊娠': 'pregnancy',
  '婚活': 'marriage-hunting',
  '子育て': 'childcare',
  '学会': 'academic-society',
  '学会入会': 'society-membership',
  '学会発表': 'academic-presentation',
  '家計': 'household-budget',
  '専攻医': 'resident',
  '専攻医 ライフハック': 'resident-lifehack',
  '専攻医 給与': 'resident-salary',
  '専攻医プログラム': 'resident-program',
  '専門医試験対策': 'specialist-exam-prep',
  '尿路感染': 'urinary-tract-infection',
  '市中病院': 'community-hospital',
  '年収': 'annual-income',
  '年次有給休暇': 'paid-leave',
  '引用文献': 'cited-references',
  '当日': 'exam-day',
  '当直': 'on-call',
  '当直バイト': 'on-call-parttime',
  '当直明け': 'post-call',
  '循環器': 'cardiology',
  '心不全': 'heart-failure',
  '心筋梗塞': 'myocardial-infarction',
  '心電図': 'ecg',
  '急性膵炎': 'acute-pancreatitis',
  '患者対応': 'patient-communication',
  '悪性リンパ腫': 'malignant-lymphoma',
  '意識障害': 'consciousness-disorder',
  '感染制御': 'infection-control',
  '感染対策': 'infection-prevention',
  '感染症': 'infectious-disease',
  '所得税': 'income-tax',
  '手取り': 'take-home-pay',
  '承認': 'approval',
  '投資': 'investment',
  '抗菌薬': 'antibiotics',
  '持ち物': 'belongings',
  '指導医': 'supervisor',
  '指導医選び': 'supervisor-selection',
  '控除': 'deduction',
  '操作方法': 'operation-guide',
  '救急': 'emergency',
  '敗血症': 'sepsis',
  '文字数': 'character-count',
  '文献引用': 'literature-citation',
  '文献検索': 'literature-search',
  '施設異動': 'facility-transfer',
  '日本内科学会': 'jsom',
  '時短': 'time-saving',
  '時給': 'hourly-rate',
  '時間管理': 'time-management',
  '更新': 'renewal',
  '有給': 'paid-leave-2',
  '期限': 'deadline',
  '期限切れ': 'expired',
  '査読委員': 'reviewer',
  '検査所見': 'examination-findings',
  '検査結果': 'test-results',
  '検診': 'health-screening',
  '求人': 'job-listing',
  '求人サイト': 'job-site',
  '流れ': 'process',
  '消化器': 'gastroenterology',
  '消化管': 'gastrointestinal',
  '準備': 'preparation-2',
  '演題': 'abstract',
  '演題登録': 'abstract-registration',
  '炎症性腸疾患': 'ibd',
  '燃え尽き症候群': 'burnout-syndrome',
  '現病歴': 'present-illness',
  '生活': 'lifestyle',
  '産休': 'maternity-leave',
  '甲状腺': 'thyroid',
  '申し込み': 'sign-up',
  '男性医師': 'male-doctor',
  '留年': 'year-extension',
  '病歴指導医': 'history-supervisor',
  '病理解剖': 'pathological-autopsy',
  '症例報告': 'case-report-2',
  '痛風': 'gout',
  '白血病': 'leukemia',
  '直前対策': 'last-minute-prep',
  '睡眠管理': 'sleep-management',
  '睡眠負債': 'sleep-debt',
  '研修プログラム': 'training-program',
  '研修先': 'training-facility',
  '研修手帳': 'training-logbook',
  '研修期間延長': 'training-extension',
  '研修評価': 'training-evaluation',
  '確定拠出年金': 'defined-contribution',
  '確定申告': 'tax-return',
  '神経': 'neurology',
  '神経内科': 'neurology-dept',
  '神経学会専門医': 'neurologist',
  '税金': 'tax',
  '節税': 'tax-saving',
  '糖尿病': 'diabetes',
  '経費': 'expenses',
  '結婚': 'marriage',
  '結婚タイミング': 'marriage-timing',
  '給与': 'salary',
  '総合内科': 'general-internal-medicine',
  '総合内科専門医': 'general-internist',
  '締め切り': 'deadline-2',
  '老後資産': 'retirement-assets',
  '考察': 'discussion',
  '肝硬変': 'liver-cirrhosis',
  '肝臓': 'liver',
  '育休': 'parental-leave',
  '育児': 'childcare-2',
  '育児休業': 'parental-leave-2',
  '肺炎': 'pneumonia',
  '肺癌': 'lung-cancer',
  '胆膵': 'hepatobiliary-pancreatic',
  '脂質異常症': 'dyslipidemia',
  '脳卒中': 'stroke',
  '脳梗塞': 'cerebral-infarction',
  '腎臓': 'nephrology',
  '膠原病': 'collagen-disease',
  '自動生成': 'auto-generation',
  '自己評価': 'self-evaluation',
  '英語論文': 'english-paper',
  '血液': 'hematology',
  '血液内科': 'hematology-dept',
  '血液専門医': 'hematologist',
  '試験会場': 'exam-venue',
  '試験対策': 'exam-prep',
  '試験日程': 'exam-schedule',
  '認知症': 'dementia',
  '論文': 'paper',
  '論文作成': 'paper-writing',
  '論文投稿': 'paper-submission',
  '論文業績': 'publications',
  '講習会': 'lecture',
  '貧血': 'anemia',
  '資格': 'qualification',
  '資産運用': 'asset-management',
  '転入': 'transfer-in',
  '転出': 'transfer-out',
  '転職': 'career-change',
  '転院': 'hospital-transfer',
  '進捗管理': 'progress-management',
  '運動習慣': 'exercise-habit',
  '過去問': 'past-exam',
  '配点': 'scoring',
  '開催スケジュール': 'event-schedule',
  '開始時期': 'start-timing',
  '間に合わない': 'running-out-of-time',
  '間質性肺炎': 'interstitial-pneumonia',
  '間質性肺疾患': 'interstitial-lung-disease',
  '関節リウマチ': 'rheumatoid-arthritis',
  '隙間時間': 'spare-time',
  '難易度': 'difficulty',
  '非常勤': 'part-time-work',
  '音声入力': 'voice-input',
  '領域別': 'by-field',
  '領域別症例数': 'field-case-count',
  '頻出テーマ': 'frequent-topics',
  '食事管理': 'diet-management',
}

// スラッグ → タグ名の逆引き
export const slugToTagMap: Record<string, string> = Object.fromEntries(
  Object.entries(tagSlugMap).map(([tag, slug]) => [slug, tag])
)

// タグ名からスラッグを取得（未登録タグはそのまま返す）
export function getTagSlug(tag: string): string {
  return tagSlugMap[tag] || tag.toLowerCase().replace(/\s+/g, '-')
}

// スラッグからタグ名を取得
export function getTagName(slug: string): string | undefined {
  return slugToTagMap[slug]
}

// サイト情報
export const siteConfig = {
  name: 'iwor',
  nameKana: 'イウォール',
  description: '医学生から医師まで、ずっと臨床のそばに',
  url: 'https://iwor.jp',
  ogImage: 'https://iwor.jp/opengraph-image',
  author: 'iwor編集部',
}
