// 臨床計算ツール設定
// 各ツールのメタデータ・カテゴリ・SEO情報を一元管理

export interface ToolSource {
  text: string
  url?: string
}

export interface ToolDefinition {
  slug: string
  name: string
  nameEn: string
  description: string
  category: ToolCategory
  tier: 1 | 2 | 3
  keywords: string[]
  relatedSlugs: string[]
  /** 最終更新日（YYYY-MM形式） */
  updatedAt?: string
  /** 参考文献・出典 */
  sources?: ToolSource[]
}

export type ToolCategory =
  | 'cardiology'
  | 'hepatology'
  | 'respiratory'
  | 'nephrology'
  | 'hematology'
  | 'infectious'
  | 'neurology'
  | 'general'
  | 'electrolyte'
  | 'antimicrobial'

export const categoryLabels: Record<ToolCategory, string> = {
  cardiology: '循環器',
  hepatology: '肝臓',
  respiratory: '呼吸器',
  nephrology: '腎臓',
  hematology: '血液',
  infectious: '感染症',
  neurology: '神経',
  general: '総合・身体計測',
  electrolyte: '電解質・輸液',
  antimicrobial: '抗菌薬・薬剤',
}

export const categoryIcons: Record<ToolCategory, string> = {
  cardiology: '❤️',
  hepatology: '🫁',
  respiratory: '🌬️',
  nephrology: '💧',
  hematology: '🩸',
  infectious: '🦠',
  neurology: '🧠',
  general: '📊',
  electrolyte: '💉',
  antimicrobial: '💊',
}

export const tools: ToolDefinition[] = [
  // ── Tier 1（16種） ──
  {
    slug: 'egfr',
    name: 'eGFR計算（CKD-EPI）',
    nameEn: 'eGFR (CKD-EPI 2021)',
    description: '血清クレアチニン値から推算糸球体濾過量（eGFR）を計算。CKD-EPI 2021式と日本人係数対応。CKDステージ判定付き。',
    category: 'nephrology',
    tier: 1,
    keywords: ['eGFR', '計算', 'CKD-EPI', '腎機能', 'CKD', 'ステージ', 'クレアチニン'],
    relatedSlugs: ['corrected-ca', 'fib-4'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Inker LA, et al. New Creatinine- and Cystatin C-Based Equations. NEJM 2021;385:1737-1749', url: 'https://doi.org/10.1056/NEJMoa2102953' },
      { text: '日本腎臓学会 CKD診療ガイドライン 2023' },
    ],
  },
  {
    slug: 'cha2ds2-vasc',
    name: 'CHA₂DS₂-VASc スコア',
    nameEn: 'CHA₂DS₂-VASc Score',
    description: '心房細動における脳卒中リスク評価。抗凝固療法の適応判断に使用。',
    category: 'cardiology',
    tier: 1,
    keywords: ['CHA2DS2-VASc', '心房細動', '脳卒中', 'リスク', '抗凝固'],
    relatedSlugs: ['chads2', 'has-bled'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Lip GY, et al. Refining clinical risk stratification for predicting stroke and thromboembolism in atrial fibrillation. Chest 2010;137(2):263-72', url: 'https://doi.org/10.1378/chest.09-1584' },
    ],
  },
  {
    slug: 'chads2',
    name: 'CHADS₂ スコア',
    nameEn: 'CHADS₂ Score',
    description: '心房細動の脳卒中リスク簡易評価。CHA₂DS₂-VAScの前身。',
    category: 'cardiology',
    tier: 1,
    keywords: ['CHADS2', '心房細動', '脳卒中'],
    relatedSlugs: ['cha2ds2-vasc', 'has-bled'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Gage BF, et al. Validation of clinical classification schemes for predicting stroke. JAMA 2001;285(22):2864-70', url: 'https://doi.org/10.1001/jama.285.22.2864' },
    ],
  },
  {
    slug: 'has-bled',
    name: 'HAS-BLED スコア',
    nameEn: 'HAS-BLED Score',
    description: '心房細動患者の出血リスク評価。抗凝固療法のリスク・ベネフィット判断に。',
    category: 'cardiology',
    tier: 1,
    keywords: ['HAS-BLED', '出血', '抗凝固', '心房細動'],
    relatedSlugs: ['cha2ds2-vasc', 'chads2'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Pisters R, et al. A novel user-friendly score (HAS-BLED) to assess 1-year risk of major bleeding. Chest 2010;138(5):1093-100', url: 'https://doi.org/10.1378/chest.10-0134' },
    ],
  },
  {
    slug: 'child-pugh',
    name: 'Child-Pugh 分類',
    nameEn: 'Child-Pugh Classification',
    description: '肝硬変の重症度分類。予後予測・治療方針決定に使用。',
    category: 'hepatology',
    tier: 1,
    keywords: ['Child-Pugh', '肝硬変', '重症度'],
    relatedSlugs: ['meld', 'fib-4'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Pugh RN, et al. Transection of the oesophagus for bleeding oesophageal varices. Br J Surg 1973;60(8):646-9', url: 'https://doi.org/10.1002/bjs.1800600817' },
    ],
  },
  {
    slug: 'meld',
    name: 'MELD スコア',
    nameEn: 'MELD Score',
    description: '末期肝疾患の重症度評価。肝移植の優先度決定に国際的に使用。',
    category: 'hepatology',
    tier: 1,
    keywords: ['MELD', '肝疾患', '肝移植'],
    relatedSlugs: ['child-pugh', 'fib-4'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Kamath PS, et al. A model to predict survival in patients with end-stage liver disease. Hepatology 2001;33(2):464-70', url: 'https://doi.org/10.1053/jhep.2001.22172' },
    ],
  },
  {
    slug: 'curb-65',
    name: 'CURB-65',
    nameEn: 'CURB-65 Score',
    description: '市中肺炎の重症度評価。入院適応の判断に使用。',
    category: 'respiratory',
    tier: 1,
    keywords: ['CURB-65', '肺炎', '重症度', 'CAP'],
    relatedSlugs: ['a-drop', 'qsofa'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Lim WS, et al. Defining community acquired pneumonia severity on presentation to hospital. Thorax 2003;58(5):377-82', url: 'https://doi.org/10.1136/thorax.58.5.377' },
    ],
  },
  {
    slug: 'a-drop',
    name: 'A-DROP',
    nameEn: 'A-DROP Score',
    description: '日本呼吸器学会の市中肺炎重症度分類。日本のガイドライン準拠。',
    category: 'respiratory',
    tier: 1,
    keywords: ['A-DROP', '肺炎', '日本呼吸器学会'],
    relatedSlugs: ['curb-65', 'qsofa'],
    updatedAt: '2026-03',
    sources: [
      { text: '日本呼吸器学会 成人肺炎診療ガイドライン 2017' },
    ],
  },
  {
    slug: 'wells-pe',
    name: 'Wells PE スコア',
    nameEn: 'Wells Score for PE',
    description: '肺塞栓症の臨床的確率評価。D-dimer検査の適応判断に。',
    category: 'respiratory',
    tier: 1,
    keywords: ['Wells', '肺塞栓', 'PE', 'D-dimer'],
    relatedSlugs: ['wells-dvt'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Wells PS, et al. Derivation of a simple clinical model to categorize patients probability of pulmonary embolism. Thromb Haemost 2000;83(3):416-20' },
    ],
  },
  {
    slug: 'wells-dvt',
    name: 'Wells DVT スコア',
    nameEn: 'Wells Score for DVT',
    description: '深部静脈血栓症の臨床的確率評価。',
    category: 'cardiology',
    tier: 1,
    keywords: ['Wells', 'DVT', '深部静脈血栓症'],
    relatedSlugs: ['wells-pe'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Wells PS, et al. Value of assessment of pretest probability of deep-vein thrombosis in clinical management. Lancet 1997;350(9094):1795-8', url: 'https://doi.org/10.1016/S0140-6736(97)08140-3' },
    ],
  },
  {
    slug: 'grace',
    name: 'GRACE スコア',
    nameEn: 'GRACE Score',
    description: '急性冠症候群（ACS）の院内死亡リスク・退院後リスク評価。',
    category: 'cardiology',
    tier: 1,
    keywords: ['GRACE', 'ACS', '急性冠症候群'],
    relatedSlugs: ['cha2ds2-vasc'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Fox KA, et al. Prediction of risk of death and myocardial infarction in the six months after presentation with acute coronary syndrome (GRACE). BMJ 2006;333(7578):1091', url: 'https://doi.org/10.1136/bmj.38985.646481.55' },
    ],
  },
  {
    slug: 'qsofa',
    name: 'qSOFA',
    nameEn: 'qSOFA Score',
    description: '敗血症のベッドサイドスクリーニング。バイタルだけで迅速評価。',
    category: 'infectious',
    tier: 1,
    keywords: ['qSOFA', '敗血症', 'sepsis'],
    relatedSlugs: ['sofa'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Singer M, et al. The Third International Consensus Definitions for Sepsis and Septic Shock (Sepsis-3). JAMA 2016;315(8):801-10', url: 'https://doi.org/10.1001/jama.2016.0287' },
    ],
  },
  {
    slug: 'sofa',
    name: 'SOFA スコア',
    nameEn: 'SOFA Score',
    description: '臓器障害の定量的評価。敗血症（Sepsis-3）の診断基準。',
    category: 'infectious',
    tier: 1,
    keywords: ['SOFA', '臓器障害', '敗血症', 'Sepsis-3'],
    relatedSlugs: ['qsofa'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Vincent JL, et al. The SOFA (Sepsis-related Organ Failure Assessment) score to describe organ dysfunction/failure. Intensive Care Med 1996;22(7):707-10', url: 'https://doi.org/10.1007/BF01709751' },
      { text: 'Singer M, et al. Sepsis-3. JAMA 2016;315(8):801-10', url: 'https://doi.org/10.1001/jama.2016.0287' },
    ],
  },
  {
    slug: 'fib-4',
    name: 'FIB-4 index',
    nameEn: 'FIB-4 Index',
    description: '肝線維化の非侵襲的評価。年齢・AST・ALT・血小板で計算。',
    category: 'hepatology',
    tier: 1,
    keywords: ['FIB-4', '肝線維化', 'NAFLD'],
    relatedSlugs: ['child-pugh', 'meld'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Sterling RK, et al. Development of a simple noninvasive index to predict significant fibrosis in patients with HIV/HCV coinfection. Hepatology 2006;43(6):1317-25', url: 'https://doi.org/10.1002/hep.21178' },
    ],
  },
  {
    slug: 'corrected-ca',
    name: '補正Ca',
    nameEn: 'Corrected Calcium',
    description: '低アルブミン血症時のカルシウム補正（Payneの式）。',
    category: 'electrolyte',
    tier: 1,
    keywords: ['補正Ca', 'カルシウム', 'アルブミン', 'Payne'],
    relatedSlugs: ['egfr'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Payne RB, et al. Interpretation of serum calcium in patients with abnormal serum proteins. Br Med J 1973;4(5893):643-6', url: 'https://doi.org/10.1136/bmj.4.5893.643' },
    ],
  },
  {
    slug: 'aa-gradient',
    name: 'A-aDO₂（肺胞気動脈血酸素分圧較差）',
    nameEn: 'A-a Gradient',
    description: '肺胞気-動脈血酸素分圧較差。低酸素血症の原因鑑別に。',
    category: 'respiratory',
    tier: 1,
    keywords: ['A-aDO2', '酸素分圧較差', '低酸素血症'],
    relatedSlugs: [],
    updatedAt: '2026-03',
    sources: [
      { text: 'Mason RJ, et al. Murray and Nadel\'s Textbook of Respiratory Medicine, 6th ed. Elsevier 2016' },
    ],
  },

  // ── Tier 2（16種） ──
  {
    slug: 'cockcroft-gault',
    name: 'Cockcroft-Gault式（CCr）',
    nameEn: 'Cockcroft-Gault (CrCl)',
    description: 'クレアチニンクリアランス推算。薬剤の腎排泄量調整に必須。',
    category: 'nephrology',
    tier: 2,
    keywords: ['Cockcroft-Gault', 'CCr', 'クレアチニンクリアランス', '腎機能'],
    relatedSlugs: ['egfr'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Cockcroft DW, Gault MH. Prediction of creatinine clearance from serum creatinine. Nephron 1976;16(1):31-41' },
    ],
  },
  {
    slug: 'bmi',
    name: 'BMI計算',
    nameEn: 'Body Mass Index',
    description: '体格指数（BMI）の計算。肥満度判定付き。',
    category: 'general',
    tier: 2,
    keywords: ['BMI', '体格指数', '肥満'],
    relatedSlugs: ['bsa'],
    updatedAt: '2026-03',
    sources: [
      { text: 'WHO. Obesity: preventing and managing the global epidemic. WHO Technical Report Series 894, 2000' },
    ],
  },
  {
    slug: 'bsa',
    name: 'BSA（体表面積）',
    nameEn: 'Body Surface Area',
    description: '体表面積の計算（Du Bois式）。薬剤投与量の算出に。',
    category: 'general',
    tier: 2,
    keywords: ['BSA', '体表面積', 'Du Bois'],
    relatedSlugs: ['bmi'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Du Bois D, Du Bois EF. A formula to estimate the approximate surface area. Arch Intern Med 1916;17:863-71' },
    ],
  },
  {
    slug: 'rcri',
    name: 'RCRI（Revised Cardiac Risk Index）',
    nameEn: 'Revised Cardiac Risk Index',
    description: '非心臓手術の周術期心血管リスク評価。術前評価に必須。',
    category: 'cardiology',
    tier: 2,
    keywords: ['RCRI', '術前評価', '心血管リスク', '周術期'],
    relatedSlugs: [],
    updatedAt: '2026-03',
    sources: [
      { text: 'Lee TH, et al. Derivation and prospective validation of a simple index for prediction of cardiac risk of major noncardiac surgery. Circulation 1999;100(10):1043-9', url: 'https://doi.org/10.1161/01.CIR.100.10.1043' },
    ],
  },
  {
    slug: 'apache2',
    name: 'APACHE II',
    nameEn: 'APACHE II Score',
    description: 'ICU入室患者の重症度・予後評価。院内死亡率予測。',
    category: 'infectious',
    tier: 2,
    keywords: ['APACHE', 'ICU', '重症度', '予後'],
    relatedSlugs: ['sofa', 'qsofa'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Knaus WA, et al. APACHE II: a severity of disease classification system. Crit Care Med 1985;13(10):818-29' },
    ],
  },
  {
    slug: 'gcs',
    name: 'GCS（Glasgow Coma Scale）',
    nameEn: 'Glasgow Coma Scale',
    description: '意識レベルの定量的評価。E+V+Mの3要素。',
    category: 'neurology',
    tier: 2,
    keywords: ['GCS', '意識レベル', 'Glasgow', '昏睡'],
    relatedSlugs: ['nihss'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Teasdale G, Jennett B. Assessment of coma and impaired consciousness. Lancet 1974;2(7872):81-4' },
    ],
  },
  {
    slug: 'nihss',
    name: 'NIHSS',
    nameEn: 'NIH Stroke Scale',
    description: '脳卒中の神経学的重症度評価。t-PA適応判断に。',
    category: 'neurology',
    tier: 2,
    keywords: ['NIHSS', '脳卒中', '重症度', 't-PA'],
    relatedSlugs: ['gcs', 'mrs', 'abcd2'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Brott T, et al. Measurements of acute cerebral infarction: a clinical examination scale. Stroke 1989;20(7):864-70' },
    ],
  },
  {
    slug: 'mrs',
    name: 'mRS（modified Rankin Scale）',
    nameEn: 'Modified Rankin Scale',
    description: '脳卒中後の機能障害度評価。転帰評価の国際標準。',
    category: 'neurology',
    tier: 2,
    keywords: ['mRS', 'Rankin', '機能障害', '脳卒中'],
    relatedSlugs: ['nihss'],
    updatedAt: '2026-03',
    sources: [
      { text: 'van Swieten JC, et al. Interobserver agreement for the assessment of handicap in stroke patients. Stroke 1988;19(5):604-7' },
    ],
  },
  {
    slug: 'karnofsky',
    name: 'Karnofsky PS',
    nameEn: 'Karnofsky Performance Status',
    description: '全身状態の評価（100〜0%）。がん患者の治療適応判断に。',
    category: 'general',
    tier: 2,
    keywords: ['Karnofsky', 'PS', '全身状態', 'がん'],
    relatedSlugs: ['ecog'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Karnofsky DA, Burchenal JH. The clinical evaluation of chemotherapeutic agents in cancer. In: MacLeod CM, ed. Evaluation of Chemotherapeutic Agents. Columbia University Press, 1949:191-205' },
    ],
  },
  {
    slug: 'ecog',
    name: 'ECOG PS',
    nameEn: 'ECOG Performance Status',
    description: '全身状態の簡易評価（0〜5）。がん臨床試験の標準。',
    category: 'general',
    tier: 2,
    keywords: ['ECOG', 'PS', '全身状態'],
    relatedSlugs: ['karnofsky'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Oken MM, et al. Toxicity and response criteria of the Eastern Cooperative Oncology Group. Am J Clin Oncol 1982;5(6):649-55' },
    ],
  },
  {
    slug: 'anion-gap',
    name: 'アニオンギャップ（AG）',
    nameEn: 'Anion Gap',
    description: 'AG計算（補正AG含む）。代謝性アシドーシスの鑑別に。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['アニオンギャップ', 'AG', 'アシドーシス', '代謝性'],
    relatedSlugs: ['corrected-ca'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Emmett M, Narins RG. Clinical use of the anion gap. Medicine 1977;56(1):38-54' },
    ],
  },
  {
    slug: 'abcd2',
    name: 'ABCD²スコア',
    nameEn: 'ABCD² Score',
    description: 'TIA後の脳梗塞リスク評価（2日・7日・90日）。',
    category: 'neurology',
    tier: 2,
    keywords: ['ABCD2', 'TIA', '脳梗塞', 'リスク'],
    relatedSlugs: ['nihss'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Johnston SC, et al. Validation and refinement of scores to predict very early stroke risk after transient ischaemic attack. Lancet 2007;369(9558):283-92', url: 'https://doi.org/10.1016/S0140-6736(07)60150-0' },
    ],
  },

  // ── 電解質・輸液計算群 ──
  {
    slug: 'maintenance-fluid',
    name: '維持輸液計算（4-2-1ルール）',
    nameEn: 'Maintenance Fluid Calculator',
    description: '体重から維持輸液量を計算。4-2-1ルール（Holliday-Segar法）。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['維持輸液', '4-2-1', 'Holliday-Segar', '輸液速度'],
    relatedSlugs: ['na-deficit', 'free-water-deficit'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Holliday MA, Segar WE. The maintenance need for water in parenteral fluid therapy. Pediatrics 1957;19(5):823-32' },
    ],
  },
  {
    slug: 'na-deficit',
    name: 'Na欠乏量計算',
    nameEn: 'Sodium Deficit Calculator',
    description: '低ナトリウム血症のNa補充量を計算。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['Na欠乏量', 'ナトリウム', '低Na血症', '補正'],
    relatedSlugs: ['na-correction-rate', 'free-water-deficit'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Adrogué HJ, Madias NE. Hyponatremia. NEJM 2000;342(21):1581-9', url: 'https://doi.org/10.1056/NEJM200005253422107' },
    ],
  },
  {
    slug: 'free-water-deficit',
    name: '自由水欠乏量',
    nameEn: 'Free Water Deficit',
    description: '高ナトリウム血症の自由水補充量を計算。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['自由水', '高Na血症', 'ナトリウム', '脱水'],
    relatedSlugs: ['na-deficit', 'na-correction-rate'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Adrogué HJ, Madias NE. Hypernatremia. NEJM 2000;342(20):1493-9', url: 'https://doi.org/10.1056/NEJM200005183422006' },
    ],
  },
  {
    slug: 'na-correction-rate',
    name: 'Na補正速度計算',
    nameEn: 'Sodium Correction Rate',
    description: 'Na補正速度の安全範囲チェック。ODS予防に。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['Na補正速度', 'ODS', '浸透圧性脱髄', '補正'],
    relatedSlugs: ['na-deficit', 'free-water-deficit'],
    updatedAt: '2026-03',
    sources: [
      { text: 'Sterns RH. Disorders of plasma sodium. NEJM 2015;372(1):55-65', url: 'https://doi.org/10.1056/NEJMra1404489' },
    ],
  },


  // ── 抗菌薬・薬剤 ──
  {
    slug: 'steroid-converter',
    name: 'ステロイド換算',
    nameEn: 'Steroid Conversion Calculator',
    description: 'ステロイド等価用量の換算（PSL, mPSL, DEX, BET, HC）。',
    category: 'antimicrobial',
    tier: 2,
    keywords: ['ステロイド', '換算', 'プレドニゾロン', 'デキサメタゾン', 'PSL'],
    relatedSlugs: [],
    updatedAt: '2026-03',
    sources: [
      { text: 'Liu D, et al. A practical guide to the monitoring and management of the complications of systemic corticosteroid therapy. Allergy Asthma Clin Immunol 2013;9(1):30' },
    ],
  },
  {
    slug: 'renal-dose-abx',
    name: '抗菌薬 腎機能別用量調整',
    nameEn: 'Renal Dose Adjustment for Antibiotics',
    description: '主要20抗菌薬のeGFR/CCr別推奨用量を表示。',
    category: 'antimicrobial',
    tier: 2,
    keywords: ['抗菌薬', '腎機能', '用量調整', 'eGFR', '減量'],
    relatedSlugs: ['egfr', 'cockcroft-gault'],
    updatedAt: '2026-03',
    sources: [
      { text: '各抗菌薬添付文書 / サンフォード感染症治療ガイド 2024' },
    ],
  },


  // ── Tier 3（専門スコア） ──
  {
    slug: 'glasgow-blatchford',
    name: 'Glasgow-Blatchford スコア',
    nameEn: 'Glasgow-Blatchford Score',
    description: '上部消化管出血の入院・介入必要性を評価。内視鏡前リスク層別化に。',
    category: 'hepatology',
    tier: 3,
    keywords: ['Glasgow-Blatchford', 'GBS', '上部消化管出血', 'GI bleeding'],
    relatedSlugs: ['aims65'],
    sources: [{ text: 'Blatchford O, et al. A risk score to predict need for treatment for upper-gastrointestinal haemorrhage. Lancet 2000;356(9238):1318-21' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'aims65',
    name: 'AIMS65 スコア',
    nameEn: 'AIMS65 Score',
    description: '上部消化管出血の院内死亡率予測。5項目の簡易評価。',
    category: 'hepatology',
    tier: 3,
    keywords: ['AIMS65', '上部消化管出血', '死亡率'],
    relatedSlugs: ['glasgow-blatchford'],
    sources: [{ text: 'Saltzman JR, et al. A simple risk score accurately predicts in-hospital mortality, length of stay, and cost in acute upper GI bleeding. Gastrointest Endosc 2011;74(6):1215-24' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'heart-score',
    name: 'HEART スコア',
    nameEn: 'HEART Score',
    description: 'ER胸痛患者のMACEリスク評価。帰宅可否判断に。',
    category: 'cardiology',
    tier: 3,
    keywords: ['HEART', '胸痛', 'MACE', 'ER'],
    relatedSlugs: ['grace', 'timi'],
    sources: [{ text: 'Six AJ, et al. The HEART score for the assessment of patients with chest pain in the emergency department. Neth Heart J 2008;16(6):191-6' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'timi',
    name: 'TIMI リスクスコア（NSTE-ACS）',
    nameEn: 'TIMI Risk Score for NSTE-ACS',
    description: '非ST上昇型ACSの14日以内イベントリスク評価。',
    category: 'cardiology',
    tier: 3,
    keywords: ['TIMI', 'ACS', 'NSTEMI', '不安定狭心症'],
    relatedSlugs: ['grace', 'heart-score'],
    sources: [{ text: 'Antman EM, et al. The TIMI risk score for unstable angina/non-ST elevation MI. JAMA 2000;284(7):835-42', url: 'https://doi.org/10.1001/jama.284.7.835' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'news2',
    name: 'NEWS2（早期警戒スコア）',
    nameEn: 'National Early Warning Score 2',
    description: '入院患者の急性増悪リスク評価。バイタル6項目で迅速スクリーニング。',
    category: 'general',
    tier: 3,
    keywords: ['NEWS', 'NEWS2', '早期警戒', 'EWS', '急変'],
    relatedSlugs: ['qsofa'],
    sources: [{ text: 'Royal College of Physicians. National Early Warning Score (NEWS) 2. RCP 2017' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'charlson',
    name: 'チャールソン併存疾患指数',
    nameEn: 'Charlson Comorbidity Index',
    description: '併存疾患に基づく10年生存率予測。臨床研究のリスク調整に。',
    category: 'general',
    tier: 3,
    keywords: ['Charlson', 'CCI', '併存疾患', 'comorbidity'],
    relatedSlugs: ['ecog', 'karnofsky'],
    sources: [{ text: 'Charlson ME, et al. A new method of classifying prognostic comorbidity. J Chronic Dis 1987;40(5):373-83' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'centor',
    name: 'Centor スコア（McIsaac変法）',
    nameEn: 'Centor Score (Modified/McIsaac)',
    description: '急性咽頭炎のA群溶連菌感染確率評価。迅速検査・抗菌薬適応判断に。',
    category: 'infectious',
    tier: 3,
    keywords: ['Centor', 'McIsaac', '咽頭炎', '溶連菌', 'GAS'],
    relatedSlugs: [],
    sources: [{ text: 'Centor RM, et al. The diagnosis of strep throat in adults in the emergency room. Med Decis Making 1981;1(3):239-46' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'caprini',
    name: 'Caprini スコア（VTEリスク）',
    nameEn: 'Caprini Score',
    description: '手術患者のVTE（静脈血栓塞栓症）リスク評価。予防策決定に。',
    category: 'cardiology',
    tier: 3,
    keywords: ['Caprini', 'VTE', '血栓予防', '周術期'],
    relatedSlugs: ['wells-pe', 'wells-dvt', 'padua'],
    sources: [{ text: 'Caprini JA. Thrombosis risk assessment as a guide to quality patient care. Dis Mon 2005;51(2-3):70-8' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'padua',
    name: 'Padua Prediction スコア',
    nameEn: 'Padua Prediction Score',
    description: '内科入院患者のVTEリスク評価。抗凝固予防の適応判断に。',
    category: 'cardiology',
    tier: 3,
    keywords: ['Padua', 'VTE', '内科入院', '血栓予防'],
    relatedSlugs: ['wells-pe', 'wells-dvt', 'caprini'],
    sources: [{ text: 'Barbar S, et al. A risk assessment model for the identification of hospitalized medical patients at risk for venous thromboembolism. J Thromb Haemost 2010;8(11):2450-7' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'mascc',
    name: 'MASCC スコア（発熱性好中球減少）',
    nameEn: 'MASCC Risk Index',
    description: '発熱性好中球減少症（FN）の重症度評価。外来治療可否判断に。',
    category: 'infectious',
    tier: 3,
    keywords: ['MASCC', '発熱性好中球減少', 'FN', 'febrile neutropenia'],
    relatedSlugs: ['qsofa'],
    sources: [{ text: 'Klastersky J, et al. The Multinational Association for Supportive Care in Cancer risk index. J Clin Oncol 2000;18(16):3038-51' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'alvarado',
    name: 'Alvarado スコア（虫垂炎）',
    nameEn: 'Alvarado Score',
    description: '急性虫垂炎の臨床的確率評価。CT適応判断に。MANTRELS score。',
    category: 'hepatology',
    tier: 3,
    keywords: ['Alvarado', 'MANTRELS', '虫垂炎', '急性腹症'],
    relatedSlugs: [],
    sources: [{ text: 'Alvarado A. A practical score for the early diagnosis of acute appendicitis. Ann Emerg Med 1986;15(5):557-64' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'perc',
    name: 'PERC ルール（PE除外）',
    nameEn: 'PERC Rule',
    description: '低リスク患者で肺塞栓症をD-dimerなしで除外。8項目すべて陰性で除外可能。',
    category: 'respiratory',
    tier: 3,
    keywords: ['PERC', '肺塞栓', 'PE除外', 'rule-out'],
    relatedSlugs: ['wells-pe'],
    sources: [{ text: 'Kline JA, et al. Clinical criteria to prevent unnecessary diagnostic testing in emergency department patients with suspected pulmonary embolism. J Thromb Haemost 2004;2(8):1247-55' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'ottawa-ankle',
    name: 'Ottawa Ankle Rules',
    nameEn: 'Ottawa Ankle Rules',
    description: '足関節・足部外傷のX線適応判断。不要な画像検査を削減。',
    category: 'general',
    tier: 3,
    keywords: ['Ottawa', '足関節', '足部', 'X線適応', '骨折'],
    relatedSlugs: [],
    sources: [{ text: 'Stiell IG, et al. A study to develop clinical decision rules for the use of radiography in acute ankle injuries. Ann Emerg Med 1992;21(4):384-90' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'rockall',
    name: 'Rockall スコア（GI出血）',
    nameEn: 'Rockall Score',
    description: '上部消化管出血の内視鏡後再出血・死亡リスク評価。',
    category: 'hepatology',
    tier: 3,
    keywords: ['Rockall', '再出血', 'GI出血', '内視鏡後'],
    relatedSlugs: ['glasgow-blatchford', 'aims65'],
    sources: [{ text: 'Rockall TA, et al. Risk assessment after acute upper gastrointestinal haemorrhage. Gut 1996;38(3):316-21' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'spesi',
    name: 'sPESI（簡易肺塞栓重症度）',
    nameEn: 'Simplified PESI',
    description: '肺塞栓症の30日死亡率予測。低リスク患者の外来治療判断に。',
    category: 'respiratory',
    tier: 3,
    keywords: ['sPESI', 'PESI', '肺塞栓', '重症度', '外来治療'],
    relatedSlugs: ['wells-pe', 'perc'],
    sources: [{ text: 'Jiménez D, et al. Simplification of the pulmonary embolism severity index for prognostication in patients with acute symptomatic pulmonary embolism. Arch Intern Med 2010;170(15):1383-9' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'phq9',
    name: 'PHQ-9（うつ病スクリーニング）',
    nameEn: 'PHQ-9',
    description: 'うつ病の重症度評価。プライマリケアでのスクリーニングに広く使用。',
    category: 'general',
    tier: 3,
    keywords: ['PHQ-9', 'うつ病', '抑うつ', 'スクリーニング'],
    relatedSlugs: ['gad7'],
    sources: [{ text: 'Kroenke K, et al. The PHQ-9: validity of a brief depression severity measure. J Gen Intern Med 2001;16(9):606-13' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'gad7',
    name: 'GAD-7（不安症スクリーニング）',
    nameEn: 'GAD-7',
    description: '全般性不安障害の重症度評価。7項目の自記式スクリーニング。',
    category: 'general',
    tier: 3,
    keywords: ['GAD-7', '不安障害', '不安', 'スクリーニング'],
    relatedSlugs: ['phq9'],
    sources: [{ text: 'Spitzer RL, et al. A brief measure for assessing generalized anxiety disorder. Arch Intern Med 2006;166(10):1092-7', url: 'https://doi.org/10.1001/archinte.166.10.1092' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'isth-dic',
    name: 'ISTH DIC スコア',
    nameEn: 'ISTH DIC Score',
    description: '播種性血管内凝固（DIC）の診断スコア。ISTH基準（国際基準）。',
    category: 'hematology',
    tier: 3,
    keywords: ['DIC', 'ISTH', '播種性血管内凝固', 'FDP', 'Dダイマー'],
    relatedSlugs: ['sofa'],
    sources: [{ text: 'Taylor FB Jr, et al. Towards definition, clinical and laboratory criteria, and a scoring system for disseminated intravascular coagulation. Thromb Haemost 2001;86(5):1327-30' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'light-criteria',
    name: 'Light基準（胸水鑑別）',
    nameEn: "Light's Criteria",
    description: '胸水が滲出性か漏出性かを鑑別。3基準のいずれか1つ該当で滲出性。',
    category: 'respiratory',
    tier: 3,
    keywords: ['Light', '胸水', '滲出性', '漏出性', '胸腔穿刺'],
    relatedSlugs: [],
    sources: [{ text: "Light RW, et al. Pleural effusions: the diagnostic separation of transudates and exudates. Ann Intern Med 1972;77(4):507-13" }],
    updatedAt: '2026-03',
  },
  // ── 追加12種（67個完成） ──
  {
    slug: 'qtc',
    name: 'QTc計算（Bazett式）',
    nameEn: 'Corrected QT Interval (Bazett)',
    description: 'QT間隔を心拍数で補正。薬剤投与前のQTc延長スクリーニングに。Bazett / Fridericia両式対応。',
    category: 'cardiology',
    tier: 1,
    keywords: ['QTc', 'Bazett', 'Fridericia', 'QT延長', 'TdP', '心電図'],
    relatedSlugs: ['cha2ds2-vasc', 'heart-score'],
    sources: [{ text: 'Bazett HC. An analysis of the time-relations of electrocardiograms. Heart 1920;7:353-70' }],
    updatedAt: '2026-03',
  },
  {
    slug: 'map',
    name: '平均動脈圧（MAP）',
    nameEn: 'Mean Arterial Pressure',
    description: '収縮期・拡張期血圧から平均動脈圧を計算。臓器灌流圧の指標。ICU管理・昇圧剤調整に。',
    category: 'cardiology',
    tier: 1,
    keywords: ['MAP', '平均動脈圧', '灌流圧', 'ICU', '血圧'],
    relatedSlugs: ['qsofa', 'sofa', 'news2'],
    updatedAt: '2026-03',
    sources: [{ text: '標準的な生理学・薬理学計算式' }],
  },
  {
    slug: 'fena',
    name: 'FENa（Na排泄率）',
    nameEn: 'Fractional Excretion of Sodium',
    description: '腎前性AKIと腎性AKIの鑑別に。尿中Na・Cr、血清Na・Crから算出。',
    category: 'nephrology',
    tier: 1,
    keywords: ['FENa', 'AKI', '急性腎障害', '腎前性', '尿中Na'],
    relatedSlugs: ['egfr', 'cockcroft-gault', 'na-deficit'],
    updatedAt: '2026-03',
    sources: [{ text: 'Espinel CH. The FENa test: use in the differential diagnosis of acute renal failure. JAMA 1976;236(6):579-81' }],
  },
  {
    slug: 'osmolality-gap',
    name: '浸透圧ギャップ',
    nameEn: 'Osmolality Gap',
    description: '実測浸透圧と計算浸透圧の差。メタノール・エチレングリコール中毒のスクリーニングに。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['浸透圧ギャップ', 'Osmolal gap', '中毒', 'メタノール', 'エチレングリコール'],
    relatedSlugs: ['anion-gap', 'na-deficit'],
    updatedAt: '2026-03',
    sources: [{ text: 'Glaser DS. Utility of the serum osmol gap in the diagnosis of methanol or ethylene glycol ingestion. Ann Emerg Med 1996;27(3):343-6' }],
  },
  {
    slug: 'winters-formula',
    name: 'Winters式（代償予測pCO2）',
    nameEn: "Winter's Formula",
    description: '代謝性アシドーシス時の予測pCO2を算出。呼吸性代償が適切か判定。血ガス解釈の必須ツール。',
    category: 'respiratory',
    tier: 2,
    keywords: ['Winters', '代償', 'pCO2', '血ガス', '代謝性アシドーシス'],
    relatedSlugs: ['anion-gap', 'aa-gradient'],
    updatedAt: '2026-03',
    sources: [{ text: 'Winters RW, et al. The natural history of renal acidosis. In: Albert MS, ed. Acid-Base and Potassium Homeostasis. 1969' }],
  },
  {
    slug: 'corrected-phenytoin',
    name: '補正フェニトイン濃度',
    nameEn: 'Corrected Phenytoin Level',
    description: '低アルブミン時のフェニトイン補正濃度を計算（Sheiner-Tozer式）。治療域判定付き。',
    category: 'antimicrobial',
    tier: 2,
    keywords: ['フェニトイン', 'Sheiner-Tozer', 'アレビアチン', '低アルブミン', 'TDM'],
    relatedSlugs: ['corrected-ca'],
    updatedAt: '2026-03',
    sources: [{ text: 'Winter ME, Tozer TN. Phenytoin. In: Evans WE, et al. Applied Pharmacokinetics, 3rd ed. Applied Therapeutics 1992' }],
  },
  {
    slug: 'ibw',
    name: '理想体重・調整体重',
    nameEn: 'Ideal Body Weight / Adjusted Body Weight',
    description: 'Devine式で理想体重、肥満患者では調整体重を算出。人工呼吸器TV設定・薬物投与量に。',
    category: 'general',
    tier: 2,
    keywords: ['IBW', '理想体重', '調整体重', 'ABW', 'Devine', '人工呼吸器'],
    relatedSlugs: ['bmi', 'bsa', 'maintenance-fluid'],
    updatedAt: '2026-03',
    sources: [{ text: 'Devine BJ. Gentamicin therapy. Drug Intell Clin Pharm 1974;8:650-5' }],
  },
  {
    slug: 'anc',
    name: '好中球数（ANC）計算',
    nameEn: 'Absolute Neutrophil Count',
    description: '白血球数と好中球割合からANCを算出。FN（発熱性好中球減少症）の判定に。',
    category: 'hematology',
    tier: 2,
    keywords: ['ANC', '好中球', 'FN', '発熱性好中球減少', '白血球'],
    relatedSlugs: ['mascc', 'sofa'],
    updatedAt: '2026-03',
    sources: [{ text: '標準的な生理学・薬理学計算式' }],
  },
  {
    slug: 'meld-na',
    name: 'MELD-Na スコア',
    nameEn: 'MELD-Na Score',
    description: 'MELD改良版。肝移植待機リストの優先順位付けに使用。Naを加味し予後予測精度向上。',
    category: 'hepatology',
    tier: 2,
    keywords: ['MELD-Na', 'MELD', '肝移植', '肝硬変', '予後'],
    relatedSlugs: ['meld', 'child-pugh'],
    updatedAt: '2026-03',
    sources: [{ text: 'Kim WR, et al. Hyponatremia and mortality among patients on the liver-transplant waiting list. NEJM 2008;359(10):1018-26', url: 'https://doi.org/10.1056/NEJMoa0801209' }],
  },
  {
    slug: 'ranson',
    name: 'Ranson基準（急性膵炎）',
    nameEn: "Ranson's Criteria",
    description: '急性膵炎の重症度評価。入院時5項目＋48時間後6項目の計11項目で予後予測。',
    category: 'general',
    tier: 3,
    keywords: ['Ranson', '急性膵炎', '重症度', '膵炎'],
    relatedSlugs: ['bisap', 'apache2'],
    updatedAt: '2026-03',
    sources: [{ text: 'Ranson JH, et al. Prognostic signs and the role of operative management in acute pancreatitis. Surg Gynecol Obstet 1974;139(1):69-81' }],
  },
  {
    slug: 'bisap',
    name: 'BISAP スコア（急性膵炎）',
    nameEn: 'BISAP Score',
    description: '急性膵炎の入院時重症度予測。5項目で簡便に評価。Ransonより早期に判定可能。',
    category: 'general',
    tier: 3,
    keywords: ['BISAP', '急性膵炎', '重症度', 'BUN', 'SIRS'],
    relatedSlugs: ['ranson', 'apache2', 'qsofa'],
    updatedAt: '2026-03',
    sources: [{ text: 'Wu BU, et al. The early prediction of mortality in acute pancreatitis: a large population-based study. Gut 2008;57(12):1698-703' }],
  },
  {
    slug: 'audit',
    name: 'AUDIT（飲酒スクリーニング）',
    nameEn: 'Alcohol Use Disorders Identification Test',
    description: 'WHOが開発した飲酒問題スクリーニング。10項目で危険飲酒・アルコール依存を評価。',
    category: 'general',
    tier: 3,
    keywords: ['AUDIT', 'アルコール', '飲酒', 'スクリーニング', '依存'],
    relatedSlugs: ['phq9', 'gad7'],
    updatedAt: '2026-03',
    sources: [{ text: 'Saunders JB, et al. Development of the Alcohol Use Disorders Identification Test (AUDIT). Addiction 1993;88(6):791-804' }],
  },
  // ── ER/ICU系追加 ──
  {
    slug: 'ldl-friedewald',
    name: 'LDL-C計算（Friedewald式）',
    nameEn: 'LDL Cholesterol (Friedewald)',
    description: 'TC・HDL-C・TGからLDL-Cを算出。TG 400以上では使用不可。non-HDL-C併記。',
    category: 'cardiology',
    tier: 1,
    keywords: ['LDL', 'Friedewald', 'コレステロール', '脂質', 'non-HDL'],
    relatedSlugs: ['bmi', 'egfr'],
    updatedAt: '2026-03',
    sources: [{ text: 'Friedewald WT, et al. Estimation of the concentration of low-density lipoprotein cholesterol in plasma. Clin Chem 1972;18(6):499-502' }],
  },
  {
    slug: 'gamma',
    name: 'γ計算（流量⇔γ換算）',
    nameEn: 'Vasopressor / Sedative Dose Calculator',
    description: '昇圧剤・強心薬・鎮静剤・麻薬・降圧剤15薬剤のγ⇔mL/h変換。希釈プリセット・カスタム薬剤対応。',
    category: 'electrolyte',
    tier: 1,
    keywords: ['γ計算', 'ガンマ', '昇圧剤', 'ドパミン', 'ノルアドレナリン', 'ICU'],
    relatedSlugs: ['map', 'qsofa', 'sofa'],
    updatedAt: '2026-03',
    sources: [{ text: '標準的な生理学・薬理学計算式' }],
  },
  {
    slug: 'parkland',
    name: 'Parkland式（熱傷輸液）',
    nameEn: 'Parkland (Baxter) Formula',
    description: '体重と熱傷面積から初期輸液量を計算。最初8時間・次16時間の投与速度表示。',
    category: 'electrolyte',
    tier: 2,
    keywords: ['Parkland', 'Baxter', '熱傷', '輸液', 'TBSA', '熱傷面積'],
    relatedSlugs: ['maintenance-fluid', 'ibw'],
    updatedAt: '2026-03',
    sources: [{ text: 'Baxter CR, Shires T. Physiological response to crystalloid resuscitation of severe burns. Ann NY Acad Sci 1968;150(3):874-94' }],
  },
  // ── HOKUTO対抗 追加9種 ──
  {
    slug: 'jcs',
    name: 'JCS（Japan Coma Scale）',
    nameEn: 'Japan Coma Scale',
    description: '日本で最も使われる意識障害の分類。I（覚醒）II（刺激で覚醒）III（刺激しても覚醒しない）の3桁表記。',
    category: 'neurology',
    tier: 1,
    keywords: ['JCS', '意識障害', '意識レベル', 'Japan Coma Scale'],
    relatedSlugs: ['gcs', 'nihss'],
    updatedAt: '2026-03',
    sources: [{ text: '太田富雄. 急性期意識障害の新しいGrading (JCS). 脳神経外科 1974;2:623-7' }],
  },
  {
    slug: 'sirs',
    name: 'SIRS（全身性炎症反応症候群）',
    nameEn: 'Systemic Inflammatory Response Syndrome',
    description: '体温・脈拍・呼吸数・白血球数の4項目で全身性炎症を評価。敗血症の定義にも使用。',
    category: 'infectious',
    tier: 1,
    keywords: ['SIRS', '敗血症', '炎症', '全身性炎症反応'],
    relatedSlugs: ['qsofa', 'sofa', 'news2'],
    updatedAt: '2026-03',
    sources: [{ text: 'Bone RC, et al. Definitions for sepsis and organ failure. Chest 1992;101(6):1644-55' }],
  },
  {
    slug: 'fio2-table',
    name: 'FiO2換算表（酸素投与量）',
    nameEn: 'FiO2 Conversion Table',
    description: '酸素流量（L/分）から推定FiO2を換算。鼻カニューラ・マスク・リザーバー付マスク対応。',
    category: 'respiratory',
    tier: 1,
    keywords: ['FiO2', '酸素', '鼻カニューラ', 'マスク', 'リザーバー', '酸素投与量'],
    relatedSlugs: ['aa-gradient', 'ibw'],
    updatedAt: '2026-03',
    sources: [{ text: '標準的な生理学・薬理学計算式' }],
  },
  {
    slug: 'harris-benedict',
    name: 'Harris-Benedict式（基礎代謝量）',
    nameEn: 'Harris-Benedict Equation (BEE/TEE)',
    description: '性別・年齢・身長・体重から基礎エネルギー消費量（BEE）と総エネルギー消費量（TEE）を算出。栄養管理の基本。',
    category: 'general',
    tier: 2,
    keywords: ['Harris-Benedict', 'BEE', 'TEE', '基礎代謝', '栄養', 'カロリー'],
    relatedSlugs: ['bmi', 'ibw', 'bsa'],
    updatedAt: '2026-03',
    sources: [{ text: 'Harris JA, Benedict FG. A biometric study of human basal metabolism. Proc Natl Acad Sci 1918;4(12):370-3' }],
  },
  {
    slug: 'nyha',
    name: 'NYHA心機能分類',
    nameEn: 'NYHA Functional Classification',
    description: '心不全の症状に基づく機能分類。I〜IVの4段階。治療方針決定に必須。',
    category: 'cardiology',
    tier: 1,
    keywords: ['NYHA', '心不全', '心機能', '分類'],
    relatedSlugs: ['cha2ds2-vasc', 'map'],
    updatedAt: '2026-03',
    sources: [{ text: 'The Criteria Committee of the New York Heart Association. Nomenclature and Criteria for Diagnosis of Diseases of the Heart and Great Vessels, 9th ed. Little, Brown 1994' }],
  },
  {
    slug: 'homa',
    name: 'HOMA-IR / HOMA-β',
    nameEn: 'Homeostasis Model Assessment',
    description: '空腹時血糖とインスリンからインスリン抵抗性（IR）と分泌能（β）を評価。糖尿病病態把握に。',
    category: 'general',
    tier: 2,
    keywords: ['HOMA-IR', 'HOMA-β', 'インスリン抵抗性', 'インスリン分泌', '糖尿病'],
    relatedSlugs: ['bmi', 'ldl-friedewald'],
    updatedAt: '2026-03',
    sources: [{ text: 'Matthews DR, et al. Homeostasis model assessment: insulin resistance and beta-cell function. Diabetologia 1985;28(7):412-9' }],
  },
  {
    slug: 'cam-icu',
    name: 'CAM-ICU（ICUせん妄評価）',
    nameEn: 'Confusion Assessment Method for the ICU',
    description: 'ICU患者のせん妄を4項目で評価。急性発症＋注意力障害＋意識変容/思考障害で判定。',
    category: 'neurology',
    tier: 2,
    keywords: ['CAM-ICU', 'せん妄', 'ICU', 'delirium'],
    relatedSlugs: ['gcs', 'jcs', 'rass'],
    updatedAt: '2026-03',
    sources: [{ text: 'Ely EW, et al. Evaluation of delirium in critically ill patients: validation of the Confusion Assessment Method for the ICU (CAM-ICU). Crit Care Med 2001;29(7):1370-9' }],
  },
  {
    slug: 'rass',
    name: 'RASS（鎮静深度評価）',
    nameEn: 'Richmond Agitation-Sedation Scale',
    description: '人工呼吸管理患者の鎮静深度を-5〜+4の10段階で評価。目標RASS 0〜-2。',
    category: 'neurology',
    tier: 2,
    keywords: ['RASS', '鎮静', 'ICU', '人工呼吸'],
    relatedSlugs: ['gcs', 'cam-icu', 'jcs'],
    updatedAt: '2026-03',
    sources: [{ text: 'Sessler CN, et al. The Richmond Agitation-Sedation Scale: validity and reliability in adult intensive care unit patients. Am J Respir Crit Care Med 2002;166(10):1338-44' }],
  },
  {
    slug: 'barthel-index',
    name: 'Barthel Index（ADL評価）',
    nameEn: 'Barthel Index',
    description: '日常生活動作（ADL）を10項目で評価。0〜100点。リハビリ目標設定・介護度判定に使用。',
    category: 'general',
    tier: 2,
    keywords: ['Barthel', 'ADL', '日常生活動作', 'リハビリ', '介護'],
    relatedSlugs: ['mrs', 'ecog', 'karnofsky'],
    updatedAt: '2026-03',
    sources: [{ text: 'Mahoney FI, Barthel DW. Functional evaluation: the Barthel Index. Md State Med J 1965;14:61-5' }],
  },
  // ===== NEW TIER 1: ER/ICU必須 =====
  { slug: 'cchr', name: 'カナダ頭部CTルール (CCHR)', nameEn: 'Canadian CT Head Rule', description: '成人軽症頭部外傷(GCS13-15)のCT適応判断。高リスク・中リスクで層別化。', category: 'neurology', tier: 1, keywords: ['CCHR','頭部CT','頭部外傷','GCS'], relatedSlugs: ['gcs'], updatedAt: '2026-03', sources: [{ text: 'Stiell IG, et al. The Canadian CT Head Rule for patients with minor head injury. Lancet 2001;357(9266):1391-6' }] },
  { slug: 'pecarn', name: 'PECARN小児頭部外傷ルール', nameEn: 'PECARN Pediatric Head Injury Rule', description: '小児頭部外傷のCT適応。2歳未満/2歳以上で基準が異なる。ciTBIリスク<0.02%なら観察可。', category: 'neurology', tier: 1, keywords: ['PECARN','小児','頭部外傷','CT適応'], relatedSlugs: ['cchr','gcs'], updatedAt: '2026-03', sources: [{ text: 'Kuppermann N, et al. Identification of children at very low risk of clinically-important brain injuries after head trauma (PECARN). Lancet 2009;374(9696):1160-70' }] },
  { slug: 'canadian-cspine', name: 'Canadian C-Spine Rule', nameEn: 'Canadian C-Spine Rule', description: '頚椎損傷の画像検査適応判断。外傷患者で頚椎CTが不要な低リスク群を同定。', category: 'neurology', tier: 1, keywords: ['CCR','頚椎','Cスパイン','外傷'], relatedSlugs: ['nexus'], updatedAt: '2026-03', sources: [{ text: 'Stiell IG, et al. The Canadian C-Spine Rule for radiography in alert and stable trauma patients. JAMA 2001;286(15):1841-8' }] },
  { slug: 'nexus', name: 'NEXUS頚椎外傷基準', nameEn: 'NEXUS Criteria', description: '頚椎外傷の画像検査不要基準。5項目すべて陰性なら頚椎画像不要。', category: 'neurology', tier: 1, keywords: ['NEXUS','頚椎','外傷','画像'], relatedSlugs: ['canadian-cspine'], updatedAt: '2026-03', sources: [{ text: 'Hoffman JR, et al. Validity of a set of clinical criteria to rule out injury to the cervical spine (NEXUS). NEJM 2000;343(2):94-9' }] },
  { slug: 'aspects', name: 'ASPECTSスコア', nameEn: 'ASPECTS', description: '急性期脳梗塞のCT早期虚血変化の定量評価。10点満点。MCA領域を10区域で評価。', category: 'neurology', tier: 1, keywords: ['ASPECTS','脳梗塞','CT','MCA','早期虚血'], relatedSlugs: ['nihss'], updatedAt: '2026-03', sources: [{ text: 'Barber PA, et al. Validity and reliability of a quantitative computed tomography score (ASPECTS). Lancet 2000;355(9216):1670-4' }] },
  { slug: 'add-risk', name: 'ADDリスクスコア', nameEn: 'Aortic Dissection Detection Risk Score', description: '大動脈解離の検査前確率評価。0-1点かつDダイマー<0.5で解離除外。', category: 'cardiology', tier: 1, keywords: ['ADD','大動脈解離','解離','Dダイマー'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Standard perioperative risk assessment' }] },
  { slug: 'lrinec', name: 'LRINECスコア', nameEn: 'LRINEC Score', description: '壊死性筋膜炎の補助診断。≧6で壊死性筋膜炎を疑う。ただし低値でも否定できない。', category: 'infectious', tier: 1, keywords: ['LRINEC','壊死性筋膜炎','軟部組織感染'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Wong CH, et al. The LRINEC score: a tool for distinguishing necrotizing fasciitis from other soft tissue infections. Crit Care Med 2004;32(7):1535-41' }] },
  { slug: 'fisher', name: 'Fisher分類', nameEn: 'Fisher Scale', description: 'SAHのCTによる脳血管攣縮リスク分類。Grade 1-4。出血パターンで評価。', category: 'neurology', tier: 1, keywords: ['Fisher','SAH','くも膜下出血','血管攣縮'], relatedSlugs: ['hunt-hess','wfns'], updatedAt: '2026-03', sources: [{ text: 'Fisher CM, et al. Relation of cerebral vasospasm to subarachnoid hemorrhage. Neurosurgery 1980;6(1):1-9' }] },
  { slug: 'hunt-hess', name: 'Hunt and Hess分類', nameEn: 'Hunt and Hess Scale', description: 'SAH重症度分類。Grade I-V。臨床症状に基づく。', category: 'neurology', tier: 1, keywords: ['Hunt','Hess','SAH','くも膜下出血','重症度'], relatedSlugs: ['fisher','wfns'], updatedAt: '2026-03', sources: [{ text: 'Hunt WE, Hess RM. Surgical risk as related to time of intervention in the repair of intracranial aneurysms. J Neurosurg 1968;28(1):14-20' }] },
  { slug: 'wfns', name: 'WFNS分類', nameEn: 'WFNS SAH Grading', description: 'SAH重症度分類（GCSベース）。Grade I-V。国際的に広く使用。', category: 'neurology', tier: 1, keywords: ['WFNS','SAH','くも膜下出血','GCS'], relatedSlugs: ['fisher','hunt-hess','gcs'], updatedAt: '2026-03', sources: [{ text: 'Drake CG. Report of World Federation of Neurological Surgeons Committee on a Universal SAH Grading Scale. J Neurosurg 1988;68(6):985-6' }] },
  { slug: 'ciwa-ar', name: 'CIWA-Arスコア', nameEn: 'CIWA-Ar', description: 'アルコール離脱症候群の重症度評価。10項目67点満点。≧20で重症。', category: 'general', tier: 1, keywords: ['CIWA','アルコール離脱','振戦せん妄','DT'], relatedSlugs: ['audit','cage'], updatedAt: '2026-03', sources: [{ text: 'Sullivan JT, et al. Assessment of alcohol withdrawal: the revised Clinical Institute Withdrawal Assessment for Alcohol scale (CIWA-Ar). Br J Addict 1989;84(11):1353-7' }] },
  { slug: 'four-score', name: 'FOURスコア', nameEn: 'FOUR Score', description: '意識障害評価（GCSの代替）。眼・運動・脳幹反射・呼吸の4項目。挿管患者にも使用可。', category: 'neurology', tier: 1, keywords: ['FOUR','意識障害','昏睡','GCS代替'], relatedSlugs: ['gcs','jcs'], updatedAt: '2026-03', sources: [{ text: 'Wijdicks EF, et al. Validation of a new coma scale: The FOUR score. Ann Neurol 2005;58(4):585-93' }] },
  { slug: 'cage', name: 'CAGEテスト', nameEn: 'CAGE Questionnaire', description: 'アルコール依存症スクリーニング。4問中2問以上陽性で依存症を疑う。', category: 'general', tier: 1, keywords: ['CAGE','アルコール','依存症','スクリーニング'], relatedSlugs: ['audit','ciwa-ar'], updatedAt: '2026-03', sources: [{ text: 'Ewing JA. Detecting alcoholism: the CAGE questionnaire. JAMA 1984;252(14):1905-7' }] },
  { slug: 'psi-port', name: 'PSI/PORTスコア', nameEn: 'Pneumonia Severity Index', description: '市中肺炎の重症度分類。20項目でClass I-Vに層別化。入院判断の指標。', category: 'respiratory', tier: 1, keywords: ['PSI','PORT','肺炎','重症度','入院'], relatedSlugs: ['curb-65','a-drop','smart-cop'], updatedAt: '2026-03', sources: [{ text: 'Fine MJ, et al. A prediction rule to identify low-risk patients with community-acquired pneumonia. NEJM 1997;336(4):243-50', url: 'https://doi.org/10.1056/NEJM199701233360402' }] },
  { slug: 'smart-cop', name: 'SMART-COP', nameEn: 'SMART-COP', description: '市中肺炎のICU/人工呼吸器/昇圧薬の必要性予測。8項目。≧3でICU考慮。', category: 'respiratory', tier: 1, keywords: ['SMART-COP','肺炎','ICU','人工呼吸器'], relatedSlugs: ['curb-65','a-drop','psi-port'], updatedAt: '2026-03', sources: [{ text: 'Charles PG, et al. SMART-COP: a tool for predicting the need for intensive respiratory or vasopressor support in community-acquired pneumonia. Clin Infect Dis 2008;47(3):375-84' }] },
  { slug: 'geneva', name: '改訂Genevaスコア', nameEn: 'Revised Geneva Score', description: 'PE診断の臨床的確率評価。Wells代替。0-3低、4-10中、≧11高リスク。', category: 'cardiology', tier: 1, keywords: ['Geneva','PE','肺塞栓','診断予測'], relatedSlugs: ['wells-pe','perc','spesi'], updatedAt: '2026-03', sources: [{ text: 'Le Gal G, et al. Prediction of pulmonary embolism in the emergency department: the revised Geneva score. Ann Intern Med 2006;144(3):165-71' }] },
  { slug: 'toast', name: 'TOAST分類', nameEn: 'TOAST Classification', description: '脳梗塞の病型分類。大血管/小血管/心原性/その他/原因不明の5型。', category: 'neurology', tier: 1, keywords: ['TOAST','脳梗塞','病型分類','アテローム','ラクナ','心原性'], relatedSlugs: ['nihss','aspects'], updatedAt: '2026-03', sources: [{ text: 'Adams HP Jr, et al. Classification of subtype of acute ischemic stroke (TOAST). Stroke 1993;24(1):35-41' }] },
  { slug: 'duke-criteria', name: 'Duke診断基準（感染性心内膜炎）', nameEn: 'Modified Duke Criteria', description: '感染性心内膜炎(IE)の診断基準。大基準・小基準の組み合わせで確定/疑い/否定。', category: 'infectious', tier: 1, keywords: ['Duke','感染性心内膜炎','IE','心内膜炎'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Li JS, et al. Proposed modifications to the Duke criteria for the diagnosis of infective endocarditis. Clin Infect Dis 2000;30(4):633-8' }] },
  { slug: 'ottawa-sah', name: 'Ottawa SAHルール', nameEn: 'Ottawa SAH Rule', description: '頭痛患者のSAH除外。6項目すべて陰性で感度100%。15歳以上の急性頭痛が対象。', category: 'neurology', tier: 1, keywords: ['Ottawa','SAH','くも膜下出血','頭痛','除外'], relatedSlugs: ['fisher','hunt-hess'], updatedAt: '2026-03', sources: [{ text: 'Perry JJ, et al. Clinical decision rules to rule out subarachnoid hemorrhage for acute headache. JAMA 2013;310(12):1248-55' }] },
  { slug: 'san-francisco-syncope', name: 'サンフランシスコ失神ルール (CHESS)', nameEn: 'San Francisco Syncope Rule', description: '失神患者の短期重大イベント予測。5項目(CHESS)。1つでも陽性なら入院検討。', category: 'cardiology', tier: 1, keywords: ['CHESS','失神','syncope','入院適応'], relatedSlugs: ['abcd2'], updatedAt: '2026-03', sources: [{ text: 'Quinn JV, et al. Derivation of the San Francisco Syncope Rule. Ann Emerg Med 2004;43(2):224-32' }] },
  { slug: 'sapsii', name: 'SAPS II', nameEn: 'SAPS II', description: 'ICU入室患者の重症度・院内死亡率予測。17項目。APACHE IIの代替として使用。', category: 'general', tier: 1, keywords: ['SAPS','ICU','重症度','死亡率'], relatedSlugs: ['apache2','sofa'], updatedAt: '2026-03', sources: [{ text: 'Le Gall JR, et al. A new Simplified Acute Physiology Score (SAPS II). JAMA 1993;270(24):2957-63' }] },
  // ===== NEW TIER 2: 病棟頻用 =====
  { slug: 'apgar', name: 'APGARスコア', nameEn: 'APGAR Score', description: '出生直後の新生児評価。1分後・5分後に5項目(外観/脈拍/しかめ面/活動/呼吸)を評価。', category: 'general', tier: 2, keywords: ['APGAR','新生児','出生','Apgar'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Apgar V. A proposal for a new method of evaluation of the newborn infant. Curr Res Anesth Analg 1953;32(4):260-7' }] },
  { slug: 'asa-ps', name: 'ASA-PS分類', nameEn: 'ASA Physical Status', description: 'アメリカ麻酔科学会による術前の全身状態分類。Class I-VI。手術リスク評価の基本。', category: 'general', tier: 2, keywords: ['ASA','PS','麻酔','術前','全身状態'], relatedSlugs: ['rcri'], updatedAt: '2026-03', sources: [{ text: 'ASA Physical Status Classification System. American Society of Anesthesiologists 2014' }] },
  { slug: 'gir', name: 'GIR（ブドウ糖投与速度）', nameEn: 'Glucose Infusion Rate', description: 'ブドウ糖投与速度の算出。低血糖管理・TPN管理に使用。通常4-6mg/kg/min目標。', category: 'electrolyte', tier: 2, keywords: ['GIR','ブドウ糖','血糖','TPN','低血糖'], relatedSlugs: ['maintenance-fluid'], updatedAt: '2026-03', sources: [{ text: '新生児学テキスト（標準的なGIR計算式）' }] },
  { slug: 'candida-score', name: 'Candidaスコア', nameEn: 'Candida Score', description: '非好中球減少ICU患者のカンジダ感染リスク。≧3で侵襲性カンジダ症を疑う。', category: 'infectious', tier: 2, keywords: ['Candida','カンジダ','真菌','ICU'], relatedSlugs: ['mascc'], updatedAt: '2026-03', sources: [{ text: 'León C, et al. A bedside scoring system ("Candida score") for early antifungal treatment in nonneutropenic critically ill patients with Candida colonization. Crit Care Med 2006;34(3):730-7' }] },
  { slug: 'cpot', name: 'CPOT', nameEn: 'Critical-Care Pain Observation Tool', description: '重症患者の疼痛評価。表情/身体動作/筋緊張/人工呼吸器順応の4項目。≧3で疼痛あり。', category: 'general', tier: 2, keywords: ['CPOT','疼痛','痛み','ICU','鎮痛'], relatedSlugs: ['rass','cam-icu'], updatedAt: '2026-03', sources: [{ text: 'Gélinas C, et al. Validation of the Critical-Care Pain Observation Tool in adult patients. Am J Crit Care 2006;15(4):420-7' }] },
  { slug: 'bps-pain', name: 'BPS（疼痛評価）', nameEn: 'Behavioral Pain Scale', description: '鎮静患者の疼痛評価。表情/上肢/人工呼吸器順応の3項目。3-12点。≧6で疼痛あり。', category: 'general', tier: 2, keywords: ['BPS','疼痛','痛み','鎮静','ICU'], relatedSlugs: ['cpot','rass'], updatedAt: '2026-03', sources: [{ text: 'Payen JF, et al. Assessing pain in critically ill sedated patients by using a behavioral pain scale. Crit Care Med 2001;29(12):2258-63' }] },
  { slug: 'cfs', name: 'CFS臨床虚弱尺度', nameEn: 'Clinical Frailty Scale', description: 'フレイル評価。1(非常に元気)〜9(終末期)の9段階。高齢者の治療方針決定に。', category: 'general', tier: 2, keywords: ['CFS','フレイル','虚弱','高齢者','Clinical Frailty'], relatedSlugs: ['barthel-index','ecog'], updatedAt: '2026-03', sources: [{ text: 'Rockwood K, et al. A global clinical measure of fitness and frailty in elderly people. CMAJ 2005;173(5):489-95' }] },
  { slug: 'hds-r', name: 'HDS-R（長谷川式）', nameEn: 'Hasegawa Dementia Scale-Revised', description: '認知機能の簡易評価。9項目30点満点。20点以下で認知症の疑い。日本で最も使用される。', category: 'neurology', tier: 2, keywords: ['HDS-R','長谷川式','認知症','認知機能'], relatedSlugs: ['gcs','jcs'], updatedAt: '2026-03', sources: [{ text: '加藤伸司, et al. 改訂長谷川式簡易知能評価スケール(HDS-R)の作成. 老年精神医学雑誌 1991;2(11):1339-47' }] },
  { slug: 'mmrc', name: '修正MRC息切れスケール', nameEn: 'mMRC Dyspnea Scale', description: 'mMRC息切れ評価。Grade 0-4。COPD重症度評価やリハビリ目標設定に使用。', category: 'respiratory', tier: 2, keywords: ['mMRC','MRC','息切れ','COPD','呼吸困難'], relatedSlugs: ['nyha','bode'], updatedAt: '2026-03', sources: [{ text: 'Bestall JC, et al. Usefulness of the Medical Research Council (MRC) dyspnoea scale. Thorax 1999;54(7):581-6' }] },
  { slug: 'gold-copd', name: 'COPD病期分類(GOLD)', nameEn: 'GOLD COPD Classification', description: 'COPD重症度分類。FEV1%に基づくGrade 1-4 + ABCD群分類。', category: 'respiratory', tier: 2, keywords: ['GOLD','COPD','FEV1','病期','重症度'], relatedSlugs: ['mmrc','bode'], updatedAt: '2026-03', sources: [{ text: 'Global Initiative for Chronic Obstructive Lung Disease (GOLD) 2024 Report' }] },
  { slug: 'bode', name: 'BODE指数', nameEn: 'BODE Index', description: 'COPD生存期間予測。BMI/FEV1%/mMRC/6分間歩行距離の4因子。', category: 'respiratory', tier: 2, keywords: ['BODE','COPD','予後','6分間歩行'], relatedSlugs: ['gold-copd','mmrc'], updatedAt: '2026-03', sources: [{ text: 'Celli BR, et al. The body-mass index, airflow obstruction, dyspnea, and exercise capacity index in COPD. NEJM 2004;350(10):1005-12', url: 'https://doi.org/10.1056/NEJMoa021322' }] },
  { slug: 'gnri', name: 'GNRI', nameEn: 'Geriatric Nutritional Risk Index', description: '栄養の予後予測指標。アルブミン値と体重から算出。<82高リスク、82-92中リスク。', category: 'general', tier: 2, keywords: ['GNRI','栄養','アルブミン','予後'], relatedSlugs: ['conut','pni'], updatedAt: '2026-03', sources: [{ text: 'Bouillanne O, et al. Geriatric Nutritional Risk Index: a new index for evaluating at-risk elderly medical patients. Am J Clin Nutr 2005;82(4):777-83' }] },
  { slug: 'conut', name: 'CONUTスコア', nameEn: 'CONUT Score', description: '栄養の予後予測指標。アルブミン/リンパ球数/T-Cholから算出。0-12点。', category: 'general', tier: 2, keywords: ['CONUT','栄養','アルブミン','リンパ球'], relatedSlugs: ['gnri','pni'], updatedAt: '2026-03', sources: [{ text: 'Ignacio de Ulíbarri J, et al. CONUT: a tool for controlling nutritional status. Clin Nutr 2005;24(5):848-55' }] },
  { slug: 'pni', name: 'PNI（予後推定栄養指数）', nameEn: 'Prognostic Nutritional Index', description: '小野寺PNI。アルブミン×10+リンパ球数×0.005。<40で手術リスク高。', category: 'general', tier: 2, keywords: ['PNI','小野寺','栄養','手術リスク'], relatedSlugs: ['gnri','conut'], updatedAt: '2026-03', sources: [{ text: 'Onodera T, et al. Prognostic nutritional index in gastrointestinal surgery of malnourished cancer patients. 日本外科学会雑誌 1984;85(9):1001-5' }] },
  { slug: 'nrs2002', name: 'NRS 2002', nameEn: 'Nutritional Risk Screening 2002', description: '入院患者の栄養スクリーニング。≧3で栄養リスクあり。ESPENの推奨ツール。', category: 'general', tier: 2, keywords: ['NRS','栄養','スクリーニング','ESPEN'], relatedSlugs: ['gnri','conut','pni'], updatedAt: '2026-03', sources: [{ text: 'Kondrup J, et al. Nutritional risk screening (NRS 2002): a new method. Clin Nutr 2003;22(3):321-36' }] },
  { slug: 'sarc-f', name: 'SARC-F', nameEn: 'SARC-F Questionnaire', description: 'サルコペニアスクリーニング。5項目(筋力/歩行/起立/階段/転倒)。≧4で疑い。', category: 'general', tier: 2, keywords: ['SARC-F','サルコペニア','筋力低下','スクリーニング'], relatedSlugs: ['cfs','barthel-index'], updatedAt: '2026-03', sources: [{ text: 'Malmstrom TK, Morley JE. SARC-F: a simple questionnaire to rapidly diagnose sarcopenia. J Am Med Dir Assoc 2013;14(8):531-2' }] },
  { slug: 'ttkg', name: 'TTKG', nameEn: 'Transtubular K Gradient', description: '尿細管カリウム濃度勾配。高K血症の腎性/非腎性の鑑別。>7で腎排泄正常。', category: 'nephrology', tier: 2, keywords: ['TTKG','カリウム','高K','低K','尿細管'], relatedSlugs: ['fena'], updatedAt: '2026-03', sources: [{ text: 'West ML, et al. New clinical approach to evaluate disorders of potassium excretion. Miner Electrolyte Metab 1986;12(4):234-8' }] },
  { slug: 'geckler', name: 'Geckler分類', nameEn: 'Geckler Classification', description: '喀痰検体の顕微鏡的評価。好中球/扁平上皮で1-6群に分類。4-5群が良質検体。', category: 'respiratory', tier: 2, keywords: ['Geckler','喀痰','グラム染色','検体品質'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Geckler RW, et al. Microscopic and bacteriological comparison of paired sputa and transtracheal aspirates. J Clin Microbiol 1977;6(4):396-9' }] },
  { slug: 'stone-score', name: 'STONEスコア', nameEn: 'STONE Score', description: '尿路結石の予測。性別/発症時間/悪心嘔吐/赤血球/疼痛の5項目。', category: 'nephrology', tier: 2, keywords: ['STONE','尿路結石','腎結石','腎疝痛'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Moore CL, et al. Derivation and validation of a clinical diagnostic model for kidney stone (STONE score). Am J Emerg Med 2014;32(2):120-6' }] },
  { slug: 'cpc', name: 'CPC/OPC', nameEn: 'Cerebral Performance Category', description: '心肺蘇生後の機能評価。CPC 1(良好)〜5(脳死)。ROSC後の神経学的予後指標。', category: 'neurology', tier: 2, keywords: ['CPC','OPC','心肺蘇生','ROSC','予後'], relatedSlugs: ['gcs','four-score'], updatedAt: '2026-03', sources: [{ text: 'Jennett B, Bond M. Assessment of outcome after severe brain damage. Lancet 1975;1(7905):480-4' }] },
  { slug: 'opioid-conversion', name: 'オピオイド換算表', nameEn: 'Opioid Conversion Table', description: 'モルヒネ経口30mgを基準としたオピオイド相互換算。緩和ケアのローテーションに必須。', category: 'general', tier: 2, keywords: ['オピオイド','モルヒネ','フェンタニル','換算','緩和ケア'], relatedSlugs: ['steroid-converter'], updatedAt: '2026-03', sources: [{ text: '各薬剤添付文書 / 日本緩和医療学会 がん疼痛の薬物療法に関するガイドライン 2020' }] },
  { slug: 'eat10', name: 'EAT-10', nameEn: 'Eating Assessment Tool', description: '簡易嚥下評価スコア。10項目。≧3で嚥下障害の疑い。スクリーニング目的。', category: 'general', tier: 2, keywords: ['EAT-10','嚥下','誤嚥','スクリーニング'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Belafsky PC, et al. Validity and reliability of the Eating Assessment Tool (EAT-10). Ann Otol Rhinol Laryngol 2008;117(12):919-24' }] },
  { slug: 'design-r', name: 'DESIGN-R 2020', nameEn: 'DESIGN-R 2020', description: '褥瘡状態評価スケール。深さ/滲出液/大きさ/炎症/肉芽/壊死/ポケットの7項目。', category: 'general', tier: 2, keywords: ['DESIGN','褥瘡','床ずれ','創傷'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: '日本褥瘡学会 DESIGN-R 2020 褥瘡経過評価用' }] },
  { slug: 'drip-score', name: 'DRIPスコア', nameEn: 'DRIP Score', description: '抗菌薬耐性市中肺炎のリスク評価。耐性菌カバーの広域抗菌薬必要性を判断。', category: 'infectious', tier: 2, keywords: ['DRIP','耐性菌','市中肺炎','MRSA','ESBL'], relatedSlugs: ['curb-65','psi-port'], updatedAt: '2026-03', sources: [{ text: '標準的な脳出血スコアリング' }] },
  { slug: 'i-road', name: 'I-ROADスコア', nameEn: 'I-ROAD Score', description: '院内肺炎の重症度分類。日本の成人肺炎診療GLで使用。A群/B群/C群に層別化。', category: 'respiratory', tier: 2, keywords: ['I-ROAD','院内肺炎','HAP','重症度'], relatedSlugs: ['curb-65','a-drop'], updatedAt: '2026-03', sources: [{ text: '日本呼吸器学会 成人肺炎診療ガイドライン 2017' }] },
  { slug: 'infusion-list', name: '輸液製剤の組成一覧', nameEn: 'IV Fluid Composition', description: '主要輸液製剤の電解質組成一覧。生食/リンゲル/1-4号液/ブドウ糖液。', category: 'electrolyte', tier: 2, keywords: ['輸液','生食','リンゲル','ブドウ糖','電解質'], relatedSlugs: ['maintenance-fluid'], updatedAt: '2026-03', sources: [{ text: '各輸液製剤添付文書' }] },
  { slug: 'holiday-segar', name: 'Holiday-Segarの小児輸液', nameEn: 'Holiday-Segar Formula', description: '小児の維持輸液量(4-2-1ルール)。体重に基づく24時間の維持輸液量計算。', category: 'electrolyte', tier: 2, keywords: ['Holiday-Segar','小児','輸液','4-2-1','維持輸液'], relatedSlugs: ['maintenance-fluid'], updatedAt: '2026-03', sources: [{ text: 'Holliday MA, Segar WE. The maintenance need for water in parenteral fluid therapy. Pediatrics 1957;19(5):823-32' }] },
  { slug: 'periop-stop', name: '周術期の中止薬一覧', nameEn: 'Perioperative Drug Discontinuation', description: '抗血栓薬・糖尿病治療薬・抗がん剤などの手術前休薬期間一覧。', category: 'general', tier: 2, keywords: ['周術期','休薬','抗血栓薬','手術前','中止薬'], relatedSlugs: ['rcri','asa-ps'], updatedAt: '2026-03', sources: [{ text: '各薬剤添付文書 / 日本循環器学会 抗血栓薬服用者に対する消化器内視鏡診療ガイドライン 2017' }] },
  { slug: 'tetanus', name: '破傷風予防', nameEn: 'Tetanus Prophylaxis', description: '外傷時の破傷風予防フロー。トキソイド/TIG投与の判断。', category: 'infectious', tier: 2, keywords: ['破傷風','トキソイド','TIG','外傷','予防'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'CDC. Tetanus: For Clinicians. 2024' }] },
  { slug: 'abpc-score', name: '非定型肺炎スコア', nameEn: 'Atypical Pneumonia Score', description: '細菌性肺炎とマイコプラズマ肺炎の鑑別。6項目中4項目以上で非定型疑い。', category: 'respiratory', tier: 2, keywords: ['非定型','マイコプラズマ','肺炎','鑑別'], relatedSlugs: ['curb-65','a-drop'], updatedAt: '2026-03', sources: [{ text: '標準的な臨床スコアリング' }] },
  { slug: 'naranjo', name: 'Naranjo評価スケール', nameEn: 'Naranjo Adverse Drug Reaction Scale', description: '薬物有害事象の因果関係評価。10項目。確実/probable/possible/unlikely。', category: 'general', tier: 2, keywords: ['Naranjo','副作用','有害事象','因果関係'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Naranjo CA, et al. A method for estimating the probability of adverse drug reactions. Clin Pharmacol Ther 1981;30(2):239-45' }] },
  { slug: 'mcmahon', name: 'McMahonスコア', nameEn: 'McMahon Score', description: '横紋筋融解症の腎不全・死亡リスク予測。≧6で高リスク。', category: 'nephrology', tier: 2, keywords: ['McMahon','横紋筋融解','CK','腎不全','ミオグロビン'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: '標準的な臨床スコアリング' }] },
  // ===== NEW TIER 3: 専門科・表/分類 =====
  { slug: 'ann-arbor', name: 'Ann Arbor分類', nameEn: 'Ann Arbor Staging', description: '悪性リンパ腫の病期分類。Stage I-IV + A/B症状。', category: 'hematology', tier: 3, keywords: ['Ann Arbor','リンパ腫','病期','ステージング'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Carbone PP, et al. Report of the Committee on Hodgkin\'s Disease Staging Classification. Cancer Res 1971;31(11):1860-1' }] },
  { slug: 'borg-scale', name: '修正ボルグスケール', nameEn: 'Modified Borg Scale', description: '息切れなど主観的運動強度の指標。0-10。リハビリテーションで使用。', category: 'respiratory', tier: 3, keywords: ['Borg','ボルグ','息切れ','運動強度'], relatedSlugs: ['mmrc','nyha'], updatedAt: '2026-03', sources: [{ text: 'Borg GA. Psychophysical bases of perceived exertion. Med Sci Sports Exerc 1982;14(5):377-81' }] },
  { slug: 'brinkman', name: 'ブリンクマン指数', nameEn: 'Brinkman Index', description: '喫煙の累積影響評価。1日本数×喫煙年数。≧400で肺癌リスク↑。', category: 'general', tier: 3, keywords: ['ブリンクマン','喫煙','本数','pack-year'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Brinkman GL, Coates EO. The effect of bronchitis, smoking, and occupation on ventilation. Am Rev Respir Dis 1963;87:684-93' }] },
  { slug: 'burn-area', name: '熱傷面積算出', nameEn: 'Burn Area Calculation', description: '9の法則・手掌法・Lund-Browder法。Parkland公式と組み合わせて輸液量決定。', category: 'general', tier: 3, keywords: ['熱傷','9の法則','手掌法','Lund','TBSA'], relatedSlugs: ['parkland'], updatedAt: '2026-03', sources: [{ text: 'Lund CC, Browder NC. The estimation of areas of burns. Surg Gynecol Obstet 1944;79:352-8' }] },
  { slug: 'child-vital', name: '小児バイタル正常範囲', nameEn: 'Pediatric Vital Signs', description: '年齢別の小児バイタルサイン一覧。心拍数/血圧/呼吸数の正常値。', category: 'general', tier: 3, keywords: ['小児','バイタル','心拍数','血圧','正常値'], relatedSlugs: ['holiday-segar'], updatedAt: '2026-03', sources: [{ text: '日本小児科学会 小児バイタルサイン基準値' }] },
  { slug: 'anaphylaxis', name: 'アナフィラキシー診断基準', nameEn: 'Anaphylaxis Criteria', description: 'WAO 2020/アナフィラキシーGL 2022の診断基準。3つの臨床基準。', category: 'general', tier: 3, keywords: ['アナフィラキシー','アレルギー','ショック','WAO'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Sampson HA, et al. Second symposium on the definition and management of anaphylaxis (WAO). J Allergy Clin Immunol 2006;117(2):391-7' }] },
  { slug: 'gustilo', name: 'Gustilo-Anderson分類', nameEn: 'Gustilo-Anderson Classification', description: '開放骨折の重症度分類。Type I/II/IIIA/IIIB/IIIC。抗菌薬選択の指標。', category: 'general', tier: 3, keywords: ['Gustilo','開放骨折','骨折','重症度'], relatedSlugs: ['tetanus'], updatedAt: '2026-03', sources: [{ text: 'Gustilo RB, Anderson JT. Prevention of infection in the treatment of one thousand and twenty-five open fractures of long bones. J Bone Joint Surg Am 1976;58(4):453-8' }] },
  { slug: 'stop-bang', name: 'STOP-Bang', nameEn: 'STOP-Bang Questionnaire', description: 'OSASスクリーニング。8項目。≧3で中等度以上のOSASリスク。', category: 'respiratory', tier: 3, keywords: ['STOP-Bang','OSAS','睡眠時無呼吸','いびき'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Chung F, et al. STOP questionnaire: a tool to screen patients for obstructive sleep apnea. Anesthesiology 2008;108(5):812-21' }] },
  { slug: 'tds', name: 'TDS（タバコ依存症スクリーニング）', nameEn: 'Tobacco Dependence Screener', description: 'ニコチン依存症スクリーニング。10項目。≧5でニコチン依存症。禁煙外来の適応判断。', category: 'general', tier: 3, keywords: ['TDS','ニコチン','禁煙','依存症','スクリーニング'], relatedSlugs: ['brinkman'], updatedAt: '2026-03', sources: [{ text: '標準的な甲状腺機能スコアリング' }] },
  { slug: 'ipss-prostate', name: 'IPSS（前立腺症状スコア）', nameEn: 'IPSS', description: '前立腺肥大症の症状評価。7項目35点。軽症(0-7)/中等症(8-19)/重症(20-35)。', category: 'general', tier: 3, keywords: ['IPSS','前立腺','排尿','前立腺肥大'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Barry MJ, et al. The American Urological Association symptom index for benign prostatic hyperplasia. J Urol 1992;148(5):1549-57' }] },
  { slug: 'siadh', name: 'SIADH診断基準', nameEn: 'SIADH Diagnostic Criteria', description: 'バソプレシン分泌過剰症の診断基準。低Na/低浸透圧/不適切な尿濃縮の3要素。', category: 'electrolyte', tier: 3, keywords: ['SIADH','低Na','バソプレシン','低ナトリウム'], relatedSlugs: ['na-correction-rate','na-deficit','hyponatremia-flow'], updatedAt: '2026-03', sources: [{ text: 'Schwartz WB, et al. A syndrome of renal sodium loss and hyponatremia probably resulting from inappropriate secretion of antidiuretic hormone. Am J Med 1957;23(4):529-42' }] },
  { slug: 'hyponatremia-flow', name: '低Na血症の診断フロー', nameEn: 'Hyponatremia Diagnostic Algorithm', description: '尿浸透圧・尿Na濃度に基づく低ナトリウム血症の鑑別フローチャート。', category: 'electrolyte', tier: 3, keywords: ['低Na','低ナトリウム','フローチャート','鑑別'], relatedSlugs: ['siadh','na-correction-rate','osmolality-gap'], updatedAt: '2026-03', sources: [{ text: 'Spasovski G, et al. Clinical practice guideline on diagnosis and treatment of hyponatraemia. Eur J Endocrinol 2014;170(3):G1-47', url: 'https://doi.org/10.1530/EJE-13-1020' }] },
  { slug: 'la-classification', name: '逆流性食道炎 改訂LA分類', nameEn: 'LA Classification of Esophagitis', description: '逆流性食道炎の内視鏡所見分類。Grade N/M/A/B/C/D。', category: 'hepatology', tier: 3, keywords: ['LA分類','逆流性食道炎','GERD','内視鏡'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Lundell LR, et al. Endoscopic assessment of oesophagitis: clinical and functional correlates (LA classification). Gut 1999;45(2):172-80' }] },
  { slug: 'murray', name: 'Murrayスコア', nameEn: 'Murray Lung Injury Score', description: '急性肺障害の重症度/ECMO適応判断。4項目。>2.5でECMO考慮。', category: 'respiratory', tier: 3, keywords: ['Murray','ARDS','ECMO','肺障害','LIS'], relatedSlugs: ['sofa','apache2'], updatedAt: '2026-03', sources: [{ text: 'Murray JF, et al. An expanded definition of the adult respiratory distress syndrome. Am Rev Respir Dis 1988;138(3):720-3' }] },
  { slug: 'westley-croup', name: 'Westleyクループスコア', nameEn: 'Westley Croup Score', description: 'クループ症候群の重症度。意識/チアノーゼ/stridor/air entry/陥没呼吸。≦2軽症。', category: 'general', tier: 3, keywords: ['Westley','クループ','小児','stridor'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Westley CR, et al. Nebulized racemic epinephrine by IPPB for the treatment of croup. Am J Dis Child 1978;132(5):484-7' }] },
  { slug: 'kawasaki', name: '川崎病の診断基準', nameEn: 'Kawasaki Disease Criteria', description: '川崎病診断の手引き改訂6版。主要6症状中5つ以上（4つ+冠動脈病変で不全型）。', category: 'general', tier: 3, keywords: ['川崎病','冠動脈','小児','診断基準'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Newburger JW, et al. Diagnosis, treatment, and long-term management of Kawasaki disease (AHA scientific statement). Circulation 2004;110(17):2747-71' }] },
  { slug: 'ibs-rome', name: 'IBS診断基準(Rome IV)', nameEn: 'Rome IV IBS Criteria', description: '過敏性腸症候群の診断基準。反復する腹痛+排便との関連。3ヶ月以上持続。', category: 'hepatology', tier: 3, keywords: ['IBS','過敏性腸症候群','Rome','腹痛','排便'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Lacy BE, et al. Rome IV criteria. Gastroenterology 2016;150(6):1393-407' }] },
  { slug: 'bishop', name: 'Bishopスコア', nameEn: 'Bishop Score', description: '子宮頚管成熟度の内診評価。5項目。≧9で誘発分娩が成功しやすい。', category: 'general', tier: 3, keywords: ['Bishop','子宮頚管','分娩','誘発','産科'], relatedSlugs: ['apgar'], updatedAt: '2026-03', sources: [{ text: 'Bishop EH. Pelvic scoring for elective induction. Obstet Gynecol 1964;24:266-8' }] },
  { slug: 'sle-criteria', name: 'SLE分類基準(2019)', nameEn: 'EULAR/ACR SLE Classification', description: 'SLE分類基準。抗核抗体陽性が入口基準。7領域22項目の重み付けスコア。≧10で分類。', category: 'general', tier: 3, keywords: ['SLE','ループス','分類基準','ANA','EULAR'], relatedSlugs: [], updatedAt: '2026-03', sources: [{ text: 'Aringer M, et al. 2019 European League Against Rheumatism/American College of Rheumatology classification criteria for systemic lupus erythematosus. Ann Rheum Dis 2019;78(9):1151-9', url: 'https://doi.org/10.1136/annrheumdis-2018-214819' }] },
  // ── 追加ツール（D章） ──
  { slug: 'drip-rate', name: '点滴速度計算', nameEn: 'IV Drip Rate Calculator', description: '輸液量・時間・滴係数から mL/h と 滴/分を計算。一般(20滴/mL)/小児用(60滴/mL)対応。', category: 'general', tier: 2, keywords: ['点滴','滴下','速度','輸液','drip'], relatedSlugs: ['maintenance-fluid','holiday-segar'], updatedAt: '2026-03', sources: [{ text: '標準的な輸液速度計算式' }] },
  { slug: 'cardiac-index', name: '心係数 (CI)', nameEn: 'Cardiac Index', description: '心拍出量をBSAで補正。2.5-4.2 L/min/m²が正常。ショックの鑑別・循環管理に必須。', category: 'cardiology', tier: 2, keywords: ['CI','心係数','心拍出量','CO','cardiac index'], relatedSlugs: ['bsa','svri','map'], updatedAt: '2026-03', sources: [{ text: '標準的な循環生理学計算式（CI = CO / BSA）' }] },
  { slug: 'svri', name: '全身血管抵抗指数 (SVRI)', nameEn: 'Systemic Vascular Resistance Index', description: 'MAP・CVP・COからSVRIを算出。ショックの4分類鑑別（分布異常性↓/心原性↑）に有用。', category: 'cardiology', tier: 2, keywords: ['SVRI','SVR','血管抵抗','ショック','hemodynamic'], relatedSlugs: ['cardiac-index','map'], updatedAt: '2026-03', sources: [{ text: '標準的な循環生理学計算式（SVRI = (MAP-CVP)/CO × 80）' }] },
  { slug: 'maddrey', name: 'Maddrey判別関数', nameEn: "Maddrey's Discriminant Function", description: 'アルコール性肝炎の重症度判定。≧32で重症→ステロイド治療適応。PT秒とビリルビンで計算。', category: 'hepatology', tier: 2, keywords: ['Maddrey','アルコール性肝炎','DF','ステロイド','肝炎'], relatedSlugs: ['meld','child-pugh'], updatedAt: '2026-03', sources: [{ text: 'Maddrey WC, et al. Corticosteroid therapy of alcoholic hepatitis. Gastroenterology 1978;75(2):193-9' }] },
  { slug: 'iron-deficit', name: '鉄欠乏量（Ganzoni式）', nameEn: 'Iron Deficit (Ganzoni Formula)', description: '鉄欠乏性貧血の鉄補充必要量を計算。静注鉄剤（フェインジェクト/フェジン）の投与量決定に。', category: 'hematology', tier: 2, keywords: ['鉄','Ganzoni','鉄欠乏','貧血','フェジン','フェインジェクト'], relatedSlugs: ['rpi'], updatedAt: '2026-03', sources: [{ text: 'Ganzoni AM. Intravenous iron-dextran: therapeutic and experimental possibilities. Schweiz Med Wochenschr 1970;100(7):301-3' }] },
  { slug: 'rpi', name: '網赤血球産生指数 (RPI)', nameEn: 'Reticulocyte Production Index', description: '貧血の原因鑑別。RPI≧2: 溶血/出血（骨髄反応あり）、<2: 産生低下。Hctで補正。', category: 'hematology', tier: 2, keywords: ['RPI','網赤血球','貧血','溶血','reticulocyte'], relatedSlugs: ['iron-deficit'], updatedAt: '2026-03', sources: [{ text: 'Standard hematology calculation (RPI = Reticulocyte % × Hct/45 / Maturation factor)' }] },
  { slug: 'nnt', name: 'NNT（治療必要例数）', nameEn: 'Number Needed to Treat', description: '1人のイベントを回避するのに必要な治療人数。ARR/RRRも同時算出。EBM必須ツール。', category: 'general', tier: 3, keywords: ['NNT','NNH','ARR','RRR','EBM','治療必要例数'], relatedSlugs: ['post-test-probability'], updatedAt: '2026-03', sources: [{ text: '標準的な臨床疫学計算式（NNT = 1/ARR）' }] },
  { slug: 'post-test-probability', name: '検査後確率（尤度比）', nameEn: 'Post-test Probability (LR)', description: '検査前確率と尤度比から検査後確率を算出。Fagan nomogram。診断推論の基本。', category: 'general', tier: 3, keywords: ['尤度比','検査後確率','Bayes','Fagan','LR','感度','特異度'], relatedSlugs: ['nnt'], updatedAt: '2026-03', sources: [{ text: 'Fagan TJ. Nomogram for Bayes theorem. NEJM 1975;293(5):257' }] },
  { slug: 'delta-gap', name: 'デルタギャップ（Delta ratio）', nameEn: 'Delta Gap / Delta-Delta', description: 'AG上昇型代謝性アシドーシスに他の酸塩基異常が合併しているか評価。ΔAG/ΔHCO3比で判定。', category: 'electrolyte', tier: 2, keywords: ['デルタ','delta','AG','アシドーシス','酸塩基','gap-gap'], relatedSlugs: ['anion-gap','winters-formula','aa-gradient'], updatedAt: '2026-03', sources: [{ text: 'Wrenn K. The delta gap: an approach to mixed acid-base disorders. Ann Emerg Med 1990;19(11):1310-3' }] },
  { slug: 'oxygen-delivery', name: '酸素運搬量 (CaO2/DO2I)', nameEn: 'Oxygen Delivery (CaO2/DO2I)', description: '動脈血酸素含量CaO2と酸素供給指数DO2Iを計算。ICUでの酸素需給バランス評価に。', category: 'respiratory', tier: 2, keywords: ['CaO2','DO2I','酸素','oxygen delivery','ICU'], relatedSlugs: ['cardiac-index','aa-gradient'], updatedAt: '2026-03', sources: [{ text: '標準的な呼吸生理学計算式（DO2 = CO × CaO2 × 10）' }] },
  // ── v6追加ツール ──
  { slug: 'plasma-osmolality', name: '血漿浸透圧（推算）', nameEn: 'Estimated Plasma Osmolality', description: 'Na・血糖・BUNから血漿浸透圧を推算。低Na/高Na血症・浸透圧ギャップの評価に。275-295 mOsm/kg が正常。', category: 'electrolyte', tier: 2, keywords: ['浸透圧','血漿浸透圧','Posm','高Na','低Na','osmolality'], relatedSlugs: ['osmolality-gap','na-correction-rate','na-deficit','hyponatremia-flow'], updatedAt: '2026-03', sources: [{ text: '標準的な生理学計算式（2×Na + BUN/2.8 + Glu/18）' }] },
  { slug: 'urine-osmolality', name: '尿浸透圧（推算）', nameEn: 'Estimated Urine Osmolality', description: '尿比重から尿浸透圧を推算。低Na血症の鑑別（ADH適切/不適切分泌）や腎濃縮能評価に。', category: 'nephrology', tier: 2, keywords: ['尿浸透圧','尿比重','Uosm','濃縮能','SIADH','希釈尿'], relatedSlugs: ['plasma-osmolality','hyponatremia-flow','siadh','fena'], updatedAt: '2026-03', sources: [{ text: '標準的な腎臓生理学推算式' }] },
  { slug: 'tsat', name: 'TSAT（トランスフェリン飽和度）', nameEn: 'Transferrin Saturation', description: '血清鉄とTIBCからTSATを算出。鉄欠乏（<20%）や鉄過剰（>45%）の評価に。貧血の鑑別に必須。', category: 'hematology', tier: 2, keywords: ['TSAT','トランスフェリン飽和度','鉄','TIBC','鉄欠乏','貧血','フェリチン'], relatedSlugs: ['iron-deficit','rpi'], updatedAt: '2026-03', sources: [{ text: '標準的な鉄代謝指標計算式（TSAT = Fe/TIBC × 100）' }] },
  { slug: 'hba1c-glucose', name: 'HbA1c ↔ 平均血糖値換算', nameEn: 'HbA1c ↔ Estimated Average Glucose', description: 'HbA1cから推定平均血糖値(eAG)、または血糖値からHbA1cを推算。NGSP/ADAG/日本の実臨床データに基づく3方式対応。', category: 'general', tier: 2, keywords: ['HbA1c','eAG','平均血糖','糖尿病','血糖コントロール','NGSP','グリコヘモグロビン'], relatedSlugs: ['homa','bmi'], updatedAt: '2026-03', sources: [{ text: 'Nathan DM, et al. Translating the A1C assay into estimated average glucose values (ADAG study). Diabetes Care 2008;31(8):1473-8', url: 'https://doi.org/10.2337/dc08-0545' }] },
]

// 実装済みツールのslug一覧（新ツール追加時にここに追加）
export const implementedTools = new Set(['gamma', 'egfr', 'cha2ds2-vasc', 'chads2', 'has-bled', 'child-pugh', 'meld', 'curb-65', 'a-drop', 'wells-pe', 'wells-dvt', 'qsofa', 'sofa', 'fib-4', 'corrected-ca', 'aa-gradient', 'grace', 'bmi', 'bsa', 'cockcroft-gault', 'gcs', 'rcri', 'anion-gap', 'abcd2', 'mrs', 'ecog', 'karnofsky', 'maintenance-fluid', 'na-deficit', 'free-water-deficit', 'nihss', 'apache2', 'na-correction-rate', 'steroid-converter', 'renal-dose-abx', 'glasgow-blatchford', 'aims65', 'heart-score', 'timi', 'news2', 'charlson', 'centor', 'caprini', 'padua', 'mascc', 'alvarado', 'perc', 'ottawa-ankle', 'rockall', 'spesi', 'phq9', 'gad7', 'isth-dic', 'light-criteria', 'qtc', 'map', 'fena', 'osmolality-gap', 'winters-formula', 'corrected-phenytoin', 'ibw', 'anc', 'meld-na', 'ranson', 'bisap', 'audit', 'ldl-friedewald', 'parkland', 'jcs', 'sirs', 'fio2-table', 'harris-benedict', 'nyha', 'homa', 'cam-icu', 'rass', 'barthel-index',
  // Tier 1 NEW
  'cchr', 'pecarn', 'canadian-cspine', 'nexus', 'aspects', 'add-risk', 'lrinec', 'fisher', 'hunt-hess', 'wfns', 'ciwa-ar', 'four-score', 'cage', 'psi-port', 'smart-cop', 'geneva', 'toast', 'duke-criteria', 'ottawa-sah', 'san-francisco-syncope', 'sapsii',
  // Tier 2
  'apgar', 'asa-ps', 'gir', 'cfs', 'opioid-conversion', 'gnri', 'conut', 'ttkg', 'holiday-segar',
  'pni', 'cpc', 'sarc-f', 'eat10', 'mmrc',
  'infusion-list', 'geckler', 'periop-stop', 'hds-r', 'candida-score',
  'cpot', 'bps-pain', 'gold-copd', 'bode', 'nrs2002', 'stone-score', 'abpc-score', 'mcmahon', 'naranjo', 'i-road', 'tetanus',
  // Tier 3
  'brinkman', 'borg-scale', 'ann-arbor', 'stop-bang', 'tds', 'gustilo', 'murray',
  'drip-score', 'ipss-prostate', 'kawasaki', 'westley-croup', 'anaphylaxis', 'siadh', 'la-classification', 'ibs-rome', 'bishop', 'burn-area', 'child-vital', 'design-r', 'sle-criteria', 'hyponatremia-flow',
  // D章追加
  'drip-rate', 'cardiac-index', 'svri', 'maddrey', 'iron-deficit', 'rpi', 'nnt', 'post-test-probability', 'delta-gap', 'oxygen-delivery',
  // v6追加
  'plasma-osmolality', 'urine-osmolality', 'tsat', 'hba1c-glucose',
])

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find(t => t.slug === slug)
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return tools.filter(t => t.category === category)
}

export function getToolsByTier(tier: 1 | 2 | 3): ToolDefinition[] {
  return tools.filter(t => t.tier === tier)
}

export function getAllToolSlugs(): string[] {
  return tools.map(t => t.slug)
}
