'use client'
import DrugCompareLayout, { CompareData } from '@/components/compare/DrugCompareLayout'

const data: CompareData = {
  slug: 'arb',
  category: '降圧薬',
  title: 'ARB（アンジオテンシンII受容体拮抗薬）比較表',
  description: 'ロサルタン・バルサルタン・カンデサルタン・オルメサルタン・テルミサルタン・アジルサルタン・イルベサルタンの7剤を比較。',
  columns: ['generic', 'brand', 'halfLife', 'metabolism', 'renalAdjust', 'features', 'evidence'],
  drugs: [
    {
      generic: 'ロサルタン',
      brand: 'ニューロタン',
      specs: '25mg/50mg/100mg 錠',
      indication: '高血圧、糖尿病性腎症',
      halfLife: '約2時間（活性代謝物6-9時間）',
      metabolism: 'CYP2C9/3A4 → 活性代謝物（E-3174）',
      renalAdjust: '重度腎障害: 慎重投与',
      features: '世界初のARB。尿酸低下作用あり（URAT1阻害）。糖尿病性腎症に対する適応あり。プロドラッグ（活性代謝物が主効果）',
      contraindication: '妊婦、アリスキレン併用（糖尿病患者）',
      evidence: 'LIFE試験、RENAAL試験（糖尿病性腎症）',
    },
    {
      generic: 'バルサルタン',
      brand: 'ディオバン',
      specs: '20mg/40mg/80mg/160mg 錠',
      indication: '高血圧',
      halfLife: '約6時間',
      metabolism: '肝代謝少。CYP関与わずか。主に未変化体で胆汁排泄',
      renalAdjust: '通常不要（胆汁排泄主体）',
      features: 'CYP関与が少なく相互作用が少ない。心不全適応あり（海外）。ARB/CCB合剤・ARB/利尿薬合剤あり',
      contraindication: '妊婦',
      evidence: 'Val-HeFT試験、VALUE試験',
    },
    {
      generic: 'カンデサルタン',
      brand: 'ブロプレス',
      specs: '2mg/4mg/8mg/12mg 錠',
      indication: '高血圧、慢性心不全（ACE阻害薬不耐例）',
      halfLife: '約9-12時間',
      metabolism: 'エステル加水分解 → 活性体。CYP関与少',
      renalAdjust: '重度腎障害: 低用量から',
      features: '日本で最も処方量が多いARB。慢性心不全の適応あり。プロドラッグ。AT1受容体への結合が強固（slow dissociation）',
      contraindication: '妊婦、重篤な肝障害',
      evidence: 'CHARM試験（心不全）、HIJ-CREATE',
    },
    {
      generic: 'オルメサルタン',
      brand: 'オルメテック',
      specs: '5mg/10mg/20mg/40mg 錠',
      indication: '高血圧',
      halfLife: '約13時間',
      metabolism: 'エステル加水分解。CYP関与なし',
      renalAdjust: '重度腎障害: 慎重投与',
      features: '強力な降圧作用。CYP非依存で相互作用が少ない。プロドラッグ。長期使用でsprue-like enteropathy（腸疾患）の報告あり（稀）',
      contraindication: '妊婦',
      evidence: 'ROADMAP試験',
    },
    {
      generic: 'テルミサルタン',
      brand: 'ミカルディス',
      specs: '20mg/40mg/80mg 錠',
      indication: '高血圧',
      halfLife: '約24時間（ARB中最長）',
      metabolism: 'グルクロン酸抱合（胆汁排泄）。CYP関与なし',
      renalAdjust: '通常不要（胆汁排泄主体）',
      features: '半減期が最長で24時間効果持続。PPARγ部分作動作用（インスリン感受性改善）。胆汁排泄主体で腎機能の影響少。トラフ/ピーク比が高い',
      contraindication: '妊婦、重篤な肝障害、胆汁分泌障害',
      evidence: 'ONTARGET試験',
    },
    {
      generic: 'アジルサルタン',
      brand: 'アジルバ',
      specs: '10mg/20mg/40mg 錠',
      indication: '高血圧',
      halfLife: '約11-15時間',
      metabolism: 'CYP2C9（一部）。主に未変化体で排泄',
      renalAdjust: '重度腎障害: 慎重投与',
      features: '最新世代のARB。AT1受容体への結合が最も強力。降圧効果が他のARBより強いとのデータあり',
      contraindication: '妊婦',
      evidence: '国内臨床試験',
    },
    {
      generic: 'イルベサルタン',
      brand: 'アバプロ/イルベタン',
      specs: '50mg/100mg/200mg 錠',
      indication: '高血圧',
      halfLife: '約11-15時間',
      metabolism: 'CYP2C9（一部）。グルクロン酸抱合',
      renalAdjust: '通常不要',
      features: '糖尿病性腎症に対するエビデンスが豊富（海外）。活性代謝物なし（プロドラッグでない）',
      contraindication: '妊婦',
      evidence: 'IDNT試験、IRMA-2試験（糖尿病性腎症）',
    },
  ],
  seoContent: [
    { heading: 'ARBの使い分けポイント', text: 'ARBは全て降圧効果を持ちますが、半減期・代謝経路・臓器保護エビデンスに差があります。心不全ではカンデサルタン（CHARM）、糖尿病性腎症ではロサルタン（RENAAL）・イルベサルタン（IDNT）にエビデンスがあります。テルミサルタンは半減期が最長で24時間効果が持続します。' },
    { heading: 'ARBとACE阻害薬の選択', text: 'ARBとACE阻害薬は同じRAS系を阻害しますが、ARBは空咳の副作用が少ない利点があります。ACE阻害薬は心不全・MI後のエビデンスが豊富で、コスト面でも有利です。ARBとACE阻害薬の併用はONTARGET試験で腎障害増加が示され、原則併用されません。' },
    { heading: '配合剤の活用', text: 'ARB/CCB配合剤やARB/利尿薬配合剤は、服薬錠数の減少によるアドヒアランス向上が期待できます。日本では多数の配合剤が使用可能で、単剤で目標血圧に達しない場合の増強に有用です。' },
  ],
  references: [
    '各薬剤の添付文書（最新版）',
    '日本高血圧学会. 高血圧治療ガイドライン 2019（JSH2019）',
    'Yusuf S et al. Telmisartan, ramipril, or both (ONTARGET). N Engl J Med 2008;358:1547-1559',
    'Brenner BM et al. Losartan in type 2 diabetes (RENAAL). N Engl J Med 2001;345:861-869',
  ],
  relatedTools: [
    { href: '/tools/calc/egfr', name: 'eGFR' },
    { href: '/tools/calc/cockcroft-gault', name: 'Cockcroft-Gault' },
    { href: '/compare/statin', name: 'スタチン比較' },
  ],
}

export default function ARBComparePage() {
  return <DrugCompareLayout data={data} />
}
