'use client'
import DrugCompareLayout, { CompareData } from '@/components/compare/DrugCompareLayout'

const data: CompareData = {
  slug: 'statin',
  category: '脂質異常症治療薬',
  title: 'スタチン比較表',
  description: 'ロスバスタチン・アトルバスタチン・ピタバスタチン等6剤を添付文書情報に基づき比較。強度分類・代謝経路・薬物相互作用を一覧。',
  columns: ['generic', 'brand', 'features', 'halfLife', 'metabolism', 'renalAdjust', 'contraindication', 'evidence'],
  drugs: [
    {
      generic: 'ロスバスタチン',
      brand: 'クレストール',
      specs: '2.5mg/5mg/10mg 錠',
      indication: '高コレステロール血症、家族性高コレステロール血症',
      halfLife: '約20時間',
      metabolism: '肝代謝少（CYP2C9 一部）、主に未変化体で排泄。水溶性',
      renalAdjust: '重度腎障害: 慎重投与（開始量を低めに）',
      features: 'ストロングスタチン。LDL低下作用が最も強力。水溶性で筋障害リスクがやや低い。CYP3A4の影響を受けにくい',
      contraindication: '活動性肝疾患、妊婦・授乳婦、シクロスポリン併用',
      evidence: 'JUPITER試験（一次予防）、METEOR試験',
    },
    {
      generic: 'アトルバスタチン',
      brand: 'リピトール',
      specs: '5mg/10mg 錠',
      indication: '高コレステロール血症、家族性高コレステロール血症',
      halfLife: '約14時間（活性代謝物含め20-30時間）',
      metabolism: 'CYP3A4（脂溶性）',
      renalAdjust: '腎機能の影響は少ない',
      features: 'ストロングスタチン。活性代謝物による持続的効果。CYP3A4阻害薬との相互作用に注意。世界で最も使用実績が多い',
      contraindication: '活動性肝疾患、妊婦・授乳婦',
      evidence: 'ASCOT-LLA、TNT試験、SPARCL試験',
    },
    {
      generic: 'ピタバスタチン',
      brand: 'リバロ',
      specs: '1mg/2mg/4mg 錠',
      indication: '高コレステロール血症、家族性高コレステロール血症',
      halfLife: '約11時間',
      metabolism: 'CYP2C9（限定的）。グルクロン酸抱合。CYP3A4関与少',
      renalAdjust: '重度腎障害: 慎重投与',
      features: 'ストロングスタチン。CYP3A4の影響をほぼ受けない（相互作用が少ない）。日本発のスタチン。HDL上昇作用あり',
      contraindication: '活動性肝疾患、妊婦、シクロスポリン併用',
      evidence: 'LIVES試験（日本）、J-PREDICT試験',
    },
    {
      generic: 'プラバスタチン',
      brand: 'メバロチン',
      specs: '5mg/10mg 錠',
      indication: '高コレステロール血症、家族性高コレステロール血症',
      halfLife: '約1.5-2時間',
      metabolism: '肝で硫酸抱合。CYP関与なし。水溶性',
      renalAdjust: '重度腎障害: 慎重投与',
      features: 'スタンダードスタチン。CYP代謝なし（相互作用が最も少ない）。水溶性で筋障害リスク低。エビデンスが豊富',
      contraindication: '活動性肝疾患、妊婦',
      evidence: 'MEGA試験（日本、一次予防）、WOSCOPS',
    },
    {
      generic: 'シンバスタチン',
      brand: 'リポバス',
      specs: '5mg/10mg/20mg 錠',
      indication: '高コレステロール血症、家族性高コレステロール血症',
      halfLife: '約2時間',
      metabolism: 'CYP3A4（脂溶性）。プロドラッグ（体内で活性化）',
      renalAdjust: '重度腎障害: 慎重投与',
      features: 'スタンダードスタチン。CYP3A4阻害薬との相互作用に最も注意。高用量でミオパチーリスク上昇',
      contraindication: '活動性肝疾患、妊婦、強力CYP3A4阻害薬併用',
      evidence: '4S試験、HPS試験（二次予防の礎）',
    },
    {
      generic: 'フルバスタチン',
      brand: 'ローコール',
      specs: '20mg/30mg 錠',
      indication: '高コレステロール血症、家族性高コレステロール血症',
      halfLife: '約1-3時間',
      metabolism: 'CYP2C9（脂溶性だがCYP3A4非依存）',
      renalAdjust: '腎機能の影響は少ない',
      features: 'スタンダードスタチン。CYP3A4非依存で相互作用が比較的少ない。LDL低下作用はスタチン中最弱',
      contraindication: '活動性肝疾患、妊婦',
      evidence: 'LIPS試験',
    },
  ],
  seoContent: [
    { heading: 'スタチンの分類と使い分け', text: 'スタチンはLDL低下作用の強さからストロングスタチン（ロスバスタチン・アトルバスタチン・ピタバスタチン）とスタンダードスタチン（プラバスタチン・シンバスタチン・フルバスタチン）に分類されます。二次予防やハイリスク患者にはストロングスタチンが示されます。' },
    { heading: 'CYP代謝と薬物相互作用', text: 'アトルバスタチン・シンバスタチンはCYP3A4で代謝されるため、マクロライド・アゾール系抗真菌薬・Ca拮抗薬等との併用に注意が必要です。ロスバスタチン・ピタバスタチン・プラバスタチンはCYP3A4の影響が少なく、相互作用が少ないのが特徴です。' },
    { heading: '筋障害のリスク', text: '横紋筋融解症はスタチンの重大な副作用です。水溶性スタチン（ロスバスタチン・プラバスタチン）は脂溶性に比べ筋への移行が少なく、リスクがやや低いとされます。腎機能低下・甲状腺機能低下症・高齢者はリスク因子です。' },
  ],
  references: [
    '各薬剤の添付文書（最新版）',
    '日本動脈硬化学会. 動脈硬化性疾患予防ガイドライン 2022',
    'Nakamura H et al. MEGA Study (primary prevention with pravastatin). Lancet 2006;368:1155-1163',
    'Baigent C et al. CTT meta-analysis. Lancet 2010;376:1670-1681',
  ],
  relatedTools: [
    { href: '/tools/calc/fib4', name: 'FIB-4' },
    { href: '/tools/calc/egfr', name: 'eGFR' },
    { href: '/tools/calc/framingham', name: 'Framingham' },
  ],
}

export default function StatinComparePage() {
  return <DrugCompareLayout data={data} />
}
